### ISSUE TITLE
Can't use labels in a single dataset

### ISSUE THREAD

**Issue by GrossoMoreira** [chartjs/chartjs-plugin-datalabels#111]
In a chart with several datasets, I want labels to be shown only on one particular dataset.
The documentation shows how to configure labels for one dataset, but that doesn't disable labels on all other datasets. Show should I go about this? Is there a way to disable labels per dataset, so I could disable labels for every dataset except the one I need labels on?
Thank you.

**Comment by simonbrunel** [comment]
Duplicated of #20 (solution in [this comment](/chartjs/chartjs-plugin-datalabels/issues/20#issuecomment-354975040))
