### ISSUE TITLE
Set data label position Chart default with Vue.js

### ISSUE THREAD

**Issue by shlomiLan** [chartjs/chartjs-plugin-datalabels#112]
How should I set the global confugotion when using with `vue js` in the docs it's:
`Chart.defaults.global.plugins.datalabels.anchor = 'end';`

I added the plugin in `main.js`:
```
import VueChart from 'vuechart';
import ChartJsPluginDataLabels from 'chartjs-plugin-datalabels';
import Vue from 'vue';

Vue.component(VueChart.name, VueChart);
Vue.component(ChartJsPluginDataLabels);
```

And I can see that it's added to the chart but I can't chnage the datalabel position.

**Comment by simonbrunel** [comment]
Did you try to import `chart.js`?

```javascript
import Chart from 'chart.js';

// ...

Chart.defaults.global.plugins.datalabels.anchor = 'end';
```

I don't know how it's supposed to be set when using the `VueChart` wrapper, so you may want to ask this question directly to the repository of this project.

**Comment by simonbrunel** [comment]
Closing, this question should be asked to the `vuechart` repository instead.
