### ISSUE TITLE
Excess record display in ChartJS

### ISSUE THREAD

**Issue by jonjie0317** [chartjs/chartjs-plugin-datalabels#115]
Have you ever encountered this kind of bug when using chart.js? I've research over the internet but didn't find any solution.

Please see the image below.

<img src="https://i.stack.imgur.com/yk4Ph.png">

Fiddle: https://jsfiddle.net/9wzcdoyt/
Stackoverflow: https://stackoverflow.com/questions/54759935/excess-record-display-in-chartjs

**Comment by simonbrunel** [comment]
@jonjie0317 it looks like a duplicate of #30, are you using `NaN` data? what versions of Chart.js and chartjs-plugin-datalabels are you using? Your jsfiddle doesn't work, can you please update it to reproduce the screenshot you post.

**Comment by jonjie0317** [comment]
@simonbrunel I updated the jsfiddle but for some reason the chart is not showing. Please see my update. Thanks.

**Comment by simonbrunel** [comment]
I'm getting the following error: `Uncaught ReferenceError: commaify is not defined`

**Comment by jonjie0317** [comment]
@simonbrunel I forgot to add that method. Please check this updated link https://jsfiddle.net/b946y1ks/

**Comment by simonbrunel** [comment]
I can't reproduce the issue your circled in red in your first comment:

![image](https://user-images.githubusercontent.com/3874900/53162041-7dfee200-35cb-11e9-97df-6575be149ef2.png)

Also, you fiddle uses v0.1.0. Try to switch to the latest (0.5.0) and check if the issue is still there.

**Comment by jonjie0317** [comment]
@simonbrunel I changed it to v0.5.0 but the problem is still there.

**Comment by jonjie0317** [comment]
@simonbrunel Sorry about this issue. Just got a problem with my data. I only need 5 items in my array, but I'm trying to push 7 items.
