### ISSUE TITLE
how to show label instead of values in nested Doughnut chart

### ISSUE THREAD

**Issue by pk091990** [chartjs/chartjs-plugin-datalabels#118]
I'm using this plugin to show labels on my nested Doughnut chart, Is there any way to show labels i.e. Good/Bad instead of its numeric value (24/16) or can show both as displaying in tooltip.
In display section i'm returning labels only, however internally its changing label in to value.

![image](https://user-images.githubusercontent.com/46436213/53808977-abf40700-3f79-11e9-9e9a-990a65a917a5.png)

![image](https://user-images.githubusercontent.com/46436213/53808723-fd4fc680-3f78-11e9-9b6b-1920f1fe7f4d.png)

**Comment by simonbrunel** [comment]
`display` is used to control the label visibility, not the "displayed" value. If you want to change the text, then you need to use the [`formatter`](https://chartjs-plugin-datalabels.netlify.com/guide/formatting.html#data-transformation) options ([codepen](https://codepen.io/simonbrunel/pen/PLbZwB)):

```javascript
formatter: function(value, ctx) {
    var label = ctx.chart.data.labels[ctx.dataIndex];
    return label + '\n' + value;
}
```

**Comment by pk091990** [comment]
Thank you for the help :)
