### ISSUE TITLE
Data labels not showing on bar charts (line works)

### ISSUE THREAD

**Issue by bitflower** [chartjs/chartjs-plugin-datalabels#12]
Hi,

I have simply added the plugin to my codebase and the labels showed up on the line chart.

However on column and bar charts there a re no labels.

My config for the charts is basic - I don't do any configuring.

I use angular-charts wrapper btw.

Do I have to handle bar charts specifically. As i noticed from your example I don't?

Thanks

**Comment by simonbrunel** [comment]
@bitflower no special configuration but you may need to adjust the [formatter](https://chartjs-plugin-datalabels.netlify.com/formatting#data-transformation) if your data have a special structure. Can you share a fiddle or website that reproduces your issue?

**Comment by bitflower** [comment]
The hint with the formatter was a good pointer. I started to "see" my data and could fix it from there.

**Comment by simonbrunel** [comment]
Can you share your data format and solution (formatter),  could be useful for others?

**Comment by bitflower** [comment]
Basically it helped me to "believe" that the data is being loaded correctly and that it is a number. Knowing this I further tweaked the color and backgroundColor options of the datalabels. With this I found out that the font and the rectangle were the same color. I then set the background to white and used the align and anchor settings to position my labels. After all it was a little journey but your plugin is awesome.

`
vm.chartOptions = {
                plugins: {
                    datalabels: {
                        display: true,
                        formatter: formatValue
                    }
                },
            };
`

`
        function formatValue(val, context) {
        
            //console.log('Column Chart', val);

            return val.toFixed(2);
        
        }
`

**Comment by simonbrunel** [comment]
Thanks @bitflower

**Comment by bitflower** [comment]
Hey @simonbrunel , now I learned how to markdown format JS code ;-)

**Comment by liubomirwm** [comment]
For me setting the clamp property of plugins -> datalabels object to true solved the issue, version 0.6.0
