### ISSUE TITLE
Integration of the patternomaly plugin

### ISSUE THREAD

**Issue by FrankW76** [chartjs/chartjs-plugin-datalabels#120]
https://github.com/ashiguruma/patternomaly

Is it possible to use this plugin in Charba ?
Or can it maybe be integrated in a future release of Charba ?

**Comment by simonbrunel** [comment]
You should ask the [Charba project](https://github.com/pepstock-org/Charba) directly

**Comment by FrankW76** [comment]
Sorry, posted in wrong project :-/
