### ISSUE TITLE
Cummulating values in the stacked charts

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [chartjs/chartjs-plugin-datalabels#124]
If there are e.g. three series in the stacked bar chart, with labels shown at the top, I'd rather seen the subtotal values instead, so these correspond to the Y axis.

The current result is IMHO quite confusing:
![image](https://user-images.githubusercontent.com/3907898/55639022-c0b9f980-57c8-11e9-910a-afc773f74b0d.png)

The total value can be determined either roughly by projecting the top edge to the Y axis or precisely by calculating all of values. If there are lot of series, the latter method is not very user-friendly.

Currently the only workaround is to provide custom labels for all the values. However, this only works unless any dataset is hidden (as the recalculation is needed in this case).

**Comment by simonbrunel** [comment]
Similar to https://github.com/chartjs/chartjs-plugin-datalabels/issues/16#issuecomment-348333846 ([example](https://jsfiddle.net/simonbrunel/507bv4cL/)).
