### ISSUE TITLE
Option to show only total sum for stacked charts

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [chartjs/chartjs-plugin-datalabels#125]
In some stacked charts it is sufficient to show just the total value. It would be nice to have such an option. Details can always be shown in the tooltip (if enabled). If there are many series, stacked chart labels are overlapped (hard to read) anyway.

**Comment by simonbrunel** [comment]
Duplicates https://github.com/chartjs/chartjs-plugin-datalabels/issues/16#issuecomment-348333846 ([example](https://jsfiddle.net/simonbrunel/qeypzsu3/)).
