### ISSUE TITLE
Deprecation hint in Getting started --> Registration page is misleading for beginners

### ISSUE THREAD

**Issue by SeppPenner** [chartjs/chartjs-plugin-datalabels#127]
The deprecation hint in the Getting started --> Registration page is a bit misleading. I guess `From version 1.x, this plugin will no longer be registered automatically (see #42 for details).` means `From version 1.x of Chart.Js, this plugin will no longer be registered automatically (see #42 for details).` and not `From version 1.x of chartjs-plugin-datalabels, this plugin will no longer be registered automatically (see #42 for details).`

In my opinion it should be stated more precisely that version 1.x of `Chart.Js` is referred and not version 1.x of the plugin (Which does not even exist at the moment). Check the link: https://chartjs-plugin-datalabels.netlify.com/guide/getting-started.html#registration

![image](https://user-images.githubusercontent.com/9639361/55723866-6314ef80-5a0a-11e9-91df-b04d8b44982c.png)

I will provide a pull request for this.

**Comment by SeppPenner** [comment]
PR: https://github.com/chartjs/chartjs-plugin-datalabels/pull/128

**Comment by simonbrunel** [comment]
@SeppPenner It means from version 1.x of this plugin, so the next major version (not released yet) as described in https://github.com/chartjs/chartjs-plugin-datalabels/issues/42#issuecomment-443709233.

**Comment by SeppPenner** [comment]
@simonbrunel Ah okay. Then the message was just misleading because version 1.0 is not yet available. Thank you for the clearification.
