### ISSUE TITLE
Issues when trying to use with Chart.Funnel.js

### ISSUE THREAD

**Issue by smelgin** [chartjs/chartjs-plugin-datalabels#132]
![imagen](https://user-images.githubusercontent.com/5010615/57239043-6c38b280-6ff0-11e9-9f24-a8c5e63efc6c.png)
datalabels works well with Chart.js 2.8+ and funnel too ... but when you mix them, it produces the error in the attached image.

**Comment by simonbrunel** [comment]
Hi @smelgin, can you please provide a test case (codepen for example)?

**Comment by smelgin** [comment]
@simonbrunel thanks for the quick reply. I saw that plugin haves some issues with recent versions of Chart.js so I will close the issue and use an horizontal barchart instead (sadly there is no other funnel chart for chart.js). 
Thanks anyway!
