### ISSUE TITLE
Unregister plugin globally in angular

### ISSUE THREAD

**Issue by rgnrw** [chartjs/chartjs-plugin-datalabels#134]
I am importing chart js datalabel in a .ts file
I want to unregister the plugin globally so i don't need to specify
plugin = null for each chart.
https://stackoverflow.com/questions/56189171/how-to-unregister-chartjs-plugin-datalabels-globally

**Comment by thanhpd** [comment]
I don't have success with unregistering the plugin either but did work out another approach that may suitable for your need until #42 is done:

- Globally disable datalabels:
`Chart.defaults.global.plugins.datalabels.display = false;`

- In the chart option, set the `display` option for the plugin to `true`. The option object will look something like this:
```javascript
{
  plugins: {
    datalabels: {
      display: true
    }
  }
}
```

**Comment by rgnrw** [comment]
@thanhpd i asked for same, globally disable is not working in .ts file after the import statement.

**Comment by simonbrunel** [comment]
@rgnrw I think your issue is related to 92771df1588e80df1d5a70cbd8d53557222c3205, which correctly exports the plugin in TS. This hasn't been released yet but you can checkout master, build and try if it fixes your issue.

**Comment by simonbrunel** [comment]
@rgnrw @thanhpd can you please guys test the latest release 0.7.0 and report if it fixes your issues?

**Comment by akshaygujar1** [comment]
0.7.0 does not fix the issue for me. The plugin imported for one of the chart gets applied to all the charts in the page.

**Comment by jonathanjames86** [comment]
Using the `unregister()` in the `app.component.ts` work for me. From there just add the plugin to the charts that need data labels.

**Comment by simonbrunel** [comment]
@akshaygujar1 did you call `Chart.plugins.unregister()` as suggested by @jonathanjames86? I'm closing this issue because I think it works as expected. If it's not the case with v0.7.0, please re-open with a link to a repo that I can use to test.
