### ISSUE TITLE
datalabels is added to the top left corner

### ISSUE THREAD

**Issue by Duarte-Gomes** [chartjs/chartjs-plugin-datalabels#135]
Hello, after the code runs, a % is added to some value on the top left corner of the graphic.
Any kind of sugestion??

```javascript
datalabels: {
    align: 'end',
    anchor: 'end',
    formatter: function (value, context) {
        return value + '%';
    }
}
```

![omage](https://user-images.githubusercontent.com/8501405/58026667-ded88080-7b0e-11e9-9a57-1f7f8d0eeba5.PNG)

**Comment by simonbrunel** [comment]
@Duarte-Gomes can you please provide a codepen that reproduces your issue?

**Comment by Duarte-Gomes** [comment]
Hello @simonbrunel thanks for the help.
I changed the formatter with your validation and is ok know.

Thanks again
