### ISSUE TITLE
Change Label Color per Dataset

### ISSUE THREAD

**Issue by eugeneborodkin** [chartjs/chartjs-plugin-datalabels#136]
I need to change the color of my Labels per Dataset (e.g. red labels for red lines, green for green, etc.), but can't find a way to do it.

Suppose I initalize ChartJS as an empty chart, and register the plugin. New series will be added dynamically. During registration, I instruct it to pick the current color index for a global array.

```
var colorpalette = ["red", "blue", "green", "magenta", "yellow", "brown", "purple", "orange", "black", "gray"];
var currseriesnum = 0;
var chart = null;

function setUpChart() {

    var ctx = document.getElementById('chartArea').getContext('2d');
    chart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: monthnames, 
            datasets: [] // Initially blank - series added dynamically with chart.update()
        }, 
        options: {
            legend: {
                display: false
            },          
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }, 
            plugins: {  // ChartsJS DataLabels initialized here
                datalabels: {
                    anchor: 'end',
                    align: 'bottom',
                    formatter: Math.round,
                    font: {
                      weight: 'bold', 
                      size: 16
                    },
                    color: colorpalette[currseriesnum] // Pick color dynamically
                }
            }           
        }
    });     

}
```

Then I add new datasets as

```
chart.data.datasets.push({
    label: keyValueSelection.label, 
    fill: false, 
    data: keyValueSelection.value, 
    borderColor: colorpalette[currseriesnum], 
    borderWidth: 2
});
chart.update();
currseriesnum++; // Increment color counter
```
But the label color always stays the same for all datasets -- red (the first one).

**Comment by simonbrunel** [comment]
`color: colorpalette[currseriesnum]` isn't dynamic, it's equivalent to `color: colorpalette[0]` because `currseriesnum` is `0` when you call `setUpChart`. That's why the `red` color is used for all datasets. Instead, you should try:

```javascript
plugins: {
    datalabels: {
        color: function(ctx) {
            // use the same color as the border
            return ctx.dataset.borderColor
        }
    }
}
```

**Comment by eugeneborodkin** [comment]
Thanks that worked!

**Comment by jorgemoraga10** [comment]
color: (context) => {
              const index = context.dataIndex;
              const dataset = context.dataset;
              const backgroundColors = dataset.backgroundColor;
              if (backgroundColors && Array.isArray(backgroundColors)) {
                return backgroundColors[index];
              } else {
                return '#202f3e'; 
              }
            },
            
        Yo hice lo siguiente y funciono para mi, en angularTS
