### ISSUE TITLE
Proper way to use ES6 import with npm package? React Chart.js 2

### ISSUE THREAD

**Issue by dbrodie122** [chartjs/chartjs-plugin-datalabels#14]
I'm using chartjs-plugin-datalabels  in my React app using [React Chart.js 2](https://github.com/jerairrest/react-chartjs-2).

I couldn't find the proper way to import the plugin and register it on the chart instance, so I ended up just doing `import 'chartjs-plugin-datalabels'` which automatically added the plugin to all charts.  Fine, that's what I was going to do anyway.  

But is there a better/more proper way?

Issues for React Chart.js 2 didn't have an answer, so I posted my solution.

**Comment by simonbrunel** [comment]
Similar to question asked in #10?

It has been initially written and tested as a regular HTML script and that's why it automatically registers to all charts. What's the reason you think `import 'chartjs-plugin-datalabels'` is not a good way?

I think you refer to this [comment](/jerairrest/react-chartjs-2/issues/201#issuecomment-345115537)

**Comment by dbrodie122** [comment]
Right.  It's the first plugin I've used with Chart.js and I think I had the assumption that it would only activate when I add it into the plugins for the chart options object.  So when it worked...I worried I was doing something wrong that might cause problems later.

Thanks for the reply!

**Comment by simonbrunel** [comment]
I would actually expect (and prefer) the same as you, something like:
```javascript
import datalabels from 'chartjs-plugin-datalabels'

new Chart('canvas-id', {
  plugins: [datalabels]
  // ...
})
```

And in case you would like it globally registered:
```javascript
import datalabels from 'chartjs-plugin-datalabels'
Chart.plugins.register(datalabels);
```

But this is not possible when importing the plugin using regular HTML `<script>`, because we can't get a reference on the "exported" plugin:
```html
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.1.0"></script>
```

I'm open to any suggestion to make that integration better.

**Comment by asmabee07** [comment]
> ```js
> plugins: [datalabels]
> ```


Hello @simonbrunel  Can you please elaborate on this? Can I use this in the options of Chartjs?
Currently, I'm using the following approach, which is not executing the way I want it to be, I'm not able to pass the sorted Data to the following code and Font is also getting the squeeze. I need it for the individual chart. Please help.

Chart.plugins.register({
        afterDraw: function(chartInstance) {
          if (chartInstance.config.options.showDatapoints) {
            var helpers = Chart.helpers;
            var ctx = chartInstance.chart.ctx;
            var fontColor = helpers.getValueOrDefault(chartInstance.config.options.showDatapoints.fontColor, chartInstance.config.options.defaultFontColor);
      
            // render the value of the chart above the bar
            ctx.font = Chart.helpers.fontString(11, 'normal', 'Helvetica Neue');
            ctx.textAlign = 'center';
            ctx.textBaseline = 'bottom';
            ctx.fillStyle = "black";
            ctx.fontWeight = 'none';
            chartInstance.data.datasets.forEach(function (dataset) {
                for (var i = 0; i < dataset.data.length; i++) {
                    var model = dataset._meta[Object.keys(dataset._meta)[0]].data[i]._model;
                    // var scaleMax = dataset._meta[Object.keys(dataset._meta)[0]].data[i]._yScale.maxHeight;
                    var yPos =  model.y + 7;
                    var xPos = model.x + 28;
                    var dataValue = (dataset.data[i]);
                    ctx.fillText(dataValue, xPos, yPos);
                }
            });
          }
        }
    });


The version: "react-chartjs-2": "^2.11.1",
Attached the Screenshot even the font is getting bold.

![Screenshot from 2021-06-15 16-20-32](https://user-images.githubusercontent.com/21172269/122040647-aee72e80-cdf5-11eb-8569-c8729fdc57ac.png)
