### ISSUE TITLE
Bug: Overlapping Labels

### ISSUE THREAD

**Issue by Rian0702** [chartjs/chartjs-plugin-datalabels#140]
Hello, 
i am having an issue with overlapping labels. 

I already tried to resolve that by changing the order of the dataset. 
If i put the Line Chart at the end of the dataset, the label of the line-chart is on top of the bar-chart (which would be correct) but the lines are behind the bar chart. 

It seems that chart.js itself is reading the dataset array different than chartjs-datalabels. 

Hiding the labels as they overlap is not an option.

In the Image below you can see the issue happening

![image](https://user-images.githubusercontent.com/11938150/60983073-9d5b9900-a339-11e9-96c0-addbcdaa99a1.png)

**Comment by simonbrunel** [comment]
@Rian0702 I think it's somehow related to the issue reported in #126. I will need to investigate how to align the display order of the datalabels with the one of the datasets. In the meantime, can you please create a codepen that reproduces your issue and that I can use as a regression test?

**Comment by simonbrunel** [comment]
Fixed in 994aa9788f4c7d67cbfb24067108272ad4bb1c1e, can you please try to build master and confirm that it fixes your issue?

**Comment by simonbrunel** [comment]
Released in version [0.7.0](/chartjs/chartjs-plugin-datalabels/releases/tag/v0.7.0).
