### ISSUE TITLE
Disable display for specific series

### ISSUE THREAD

**Issue by MateusORGM** [chartjs/chartjs-plugin-datalabels#143]
![image](https://user-images.githubusercontent.com/12170723/61485853-8be94100-a978-11e9-83b4-b35d6e8ce52a.png)
We need to disable labels for the second series of our Charts. We can disable for specific dataset but not for specific series of all datasets. Checked all other issues but couldn't find answers.

We use override to set preferences for the second series of our chart but didn't really work.
![image](https://user-images.githubusercontent.com/12170723/61486112-1631a500-a979-11e9-943b-817d9ebbd307.png)

**Comment by simonbrunel** [comment]
@MateusORGM what are "series" vs "datasets"? can you please create a codepen that reproduces your issue and post a screenshot of the result you are expecting?

**Comment by simonbrunel** [comment]
Closing as outdated, feel free to re-open with the requested additional info.
