### ISSUE TITLE
Can I have custom text?

### ISSUE THREAD

**Issue by rajan77** [chartjs/chartjs-plugin-datalabels#147]
Hello

Instead of data inside the labels, for a polar chart, can I use this plugin to have my own text (preferably different text for each label)? I will show the legend default from chart.js anyway

Thanks in advance

R

**Comment by simonbrunel** [comment]
See the ["Custom Labels"](https://chartjs-plugin-datalabels.netlify.com/guide/formatting.html#custom-labels) documentation section.
