### ISSUE TITLE
Overlapping labels for smaller values

### ISSUE THREAD

**Issue by Danyx1980** [chartjs/chartjs-plugin-datalabels#148]
![image](https://user-images.githubusercontent.com/7244749/63369488-15ac7580-c34e-11e9-8227-9475817daa57.png)

I've got some overlapping labels that I need to show, `overlap: "auto"` won't do the trick for me as my client needs the data to be shown. Is there any way to programatically set the positioning/padding of the labels? I've been playing around with different methods but I can't find a way to just push them a little further.

**Comment by simonbrunel** [comment]
Closing in favor of #49. Unfortunately, preventing overlap by re-arranging labels is not implemented.
