### ISSUE TITLE
Pie DataLabel Error

### ISSUE THREAD

**Issue by novoa97** [chartjs/chartjs-plugin-datalabels#150]
Good morning,

I try to set a datalabel in my pie chart and I get the following error:
`"errorMessage": "Cannot read property 'x' of null",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError: Cannot read property 'x' of null",
        "    at orient (/working/node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js:155:18)"`

My chart's configuration:

`

const configuration = {

        type: 'pie',
        data: {
            labels: label,
            datasets: [{
                data: data,
                backgroundColor: color,
            }]
        },
        options: {
            legend: {
                labels: {
                    fontSize: 25,
                    fontColor: '#000000'
    }
            },
            plugins: {
                datalabels: {
                    formatter: (value, ctx) => {
                      let sum = 0;
                      let dataArr = ctx.chart.data.datasets[0].data;
                      dataArr.map(data => {
                          sum += data;
                      });
                      let percentage = (value*100 / sum).toFixed(2)+"%";
                      return percentage;            
                    },
                    color: '#fff',
                         }
            },
        }

`

**Comment by novoa97** [comment]
Solved

Version of charts.js before: 2.8.0
Version of charts.js after: 2.7.3

**Comment by simonbrunel** [comment]
Does that mean it didn't work with Chart.js 2.8? If so, it's either a bug in this plugin or a regression in Chart.js. Can you create a codepen that reproduces your issue?
