### ISSUE TITLE
How can you display dataLabels on top of the chart? 

### ISSUE THREAD

**Issue by paufar** [chartjs/chartjs-plugin-datalabels#154]
I am using the dataLabels plugin to display datalabels on top of my charts. I managed to achieve this on a line chart as you can see here: https://codepen.io/paufar/pen/VOpZGQ

But when changing from a line to a bar chart, the dataLabels are no longer at the top of the chart. Anyway that this could be amended to cater for barcharts as well?

**Comment by kurkle** [comment]
Labels do not need to be same as values. So: https://codepen.io/kurkle/pen/JjjWvGb

Important part:
```js
data: [9, 10, 3, 5, 2, 3, 8].map(x => {
          return { y: 0, label: x };
        }),
```

So dataset containing is all zeros for value.

**Comment by kurkle** [comment]
Ok, just add `anchor: 'end'` to your original pen then: https://codepen.io/kurkle/pen/ZEEeRVx

**Comment by paufar** [comment]
Thanks!
