### ISSUE TITLE
How to make inner paddings from canvas to label

### ISSUE THREAD

**Issue by iwonz** [chartjs/chartjs-plugin-datalabels#158]
Hi, in start i have to say that i saw https://github.com/chartjs/chartjs-plugin-datalabels/issues/88.
I have the same problem, but setting layout paddings doesn't suit me. In my case i have gridLines.
![image](https://user-images.githubusercontent.com/17701819/68194192-a5fd6c80-ffc5-11e9-902f-1cd603798198.png)
I have created pen with example (https://codepen.io/iwonz/pen/zYYRVpr). As you can see, if i add layout paddings it affects height of gridlines. I need something like inner paddings.

Question in stackoverflow https://stackoverflow.com/questions/58708612/how-to-make-inner-paddings-from-canvas-in-chart-js.

**Comment by simonbrunel** [comment]
Hi @iwonz! Sorry for the late reply. I don't think there is an easy way for this plugin to hook into the scale layout to add extra margins on top / bottom. It would require to change the scale min / max based on pixel sizes which is quite hacky IMO.

Not sure if there is such options already but we could introduce a new `scale.padding` which would extend the scale limits. Though it's been a while I didn't use Chart.js, so maybe it's better report this issue in the main repo. @kurle @etimberg?

As a *not* nice workaround, you could try to set explicit min / max to your scale so the lines never reach the top / bottom of the chart area?

```js
yAxes: [{ 
  ticks: {
    max: CALCULATED_MAX * 1.1,
    min: CALCULATED_MIN * 1.1
  }
}]
```

Suggestions to make this plugin to work better for that use case are welcome (feature / options).
