### ISSUE TITLE
One label for one stacked bar

### ISSUE THREAD

**Issue by LeoDupont** [chartjs/chartjs-plugin-datalabels#16]
Hi,

I have a horizontal stacked bar chart which looks like this: 

![chrome_2017-11-30_14-51-19](https://user-images.githubusercontent.com/29914053/33434023-36401b6c-d5de-11e7-846d-5b82abbc795e.png)

And I would like to display the sum of each stacked bar, like so: 

![chrome_2017-11-30_14-50-04](https://user-images.githubusercontent.com/29914053/33434044-4926d4dc-d5de-11e7-9bfb-c8f37d5dda9b.png)

I managed to get this result by returning an empty string for datasets that are not the last one (`datasetIndex`), and computing the sum for each bar (`dataIndex`): 
```typescript
plugins: {
	datalabels: {
		formatter: (value, ctx) => {
			let datasets = ctx.chart.data.datasets; // Tried `.filter(ds => !ds._meta.hidden);` without success
			if (ctx.datasetIndex === datasets.length - 1) {
				let sum = 0;
				datasets.map(dataset => {
					sum += dataset.data[ctx.dataIndex];
				});
				return sum.toLocaleString(/* ... */);
			}
			else {
				return '';
			}

		},
		anchor: 'end',
		align: 'end'
	}
}
```

It works great, but if I toggle off one dataset (via the chart's legend), the result is less great: 

- if I toggle off the first dataset, I still have the sum of the two datasets as a label: 
  
  ![chrome_2017-11-30_15-57-51](https://user-images.githubusercontent.com/29914053/33437189-6ffe1a12-d5e7-11e7-97f2-46ce51c26987.png)

- if I toggle off the last dataset, I don't have a label anymore:
  
  ![chrome_2017-11-30_15-59-59](https://user-images.githubusercontent.com/29914053/33437229-915f3bb4-d5e7-11e7-8c02-b4b11dd64b78.png)

As I commented in my code snippet, I tried to filter out the datasets with the `_meta.hidden` metadata, but it seems that the `formatter` function is not called again when toggleing datasets via the chart's legend.

Is there a better way to use datalabels with stacked bar charts? Or does anyone have an idea to make it work?

**Comment by simonbrunel** [comment]
Hi @LeoDupont. Can you build a jsfiddle (or similar) with your current chart config and data? It would help to investigate a solution.

`formatter` should be called when toggling dataset visiblity but `_meta.hidden` is private and actually doesn't describe the actual dataset visibility, you should use `chart.isDatasetVisible(index)` instead.

**Comment by LeoDupont** [comment]
Hello @simonbrunel, thank you for your answer.

I can confirm `formatter` is called when toggling dataset visibility (my bad).

Regarding `_meta.hidden`, I was also mistaken, the correct syntax being `_meta[0].hidden` (my bad, too).
I tried to use `chart.isDatasetVisible(index)` but it turned out `ctx.dataset` has no `datasetIndex` property, so I could not filter this way. Unless I missed that property?
So I chose to stick to `_meta[0].hidden`.

Finally, my condition `if (ctx.datasetIndex === datasets.length - 1)` could not work correctly because if I hide the first dataset, the last one has the index 1 whereas my `datasets` array is 1-item long, so its last index is 0...

Here is my final snippet, which works as intended: 
```typescript
plugins: {
	datalabels: {
		formatter: (value, ctx) => {
			
			// Array of visible datasets :
			let datasets = ctx.chart.data.datasets.filter(
				ds => !ds._meta[0].hidden
				// ds => ctx.chart.isDatasetVisible(ds.datasetIndex) // <-- does not work
			);
			
			// If this is the last visible dataset of the bar :
			if (datasets.indexOf(ctx.dataset) === datasets.length - 1) {
				let sum = 0;
				datasets.map(dataset => {
					sum += dataset.data[ctx.dataIndex];
				});
				return sum.toLocaleString(/* ... */);
			}
			else {
				return '';
			}
		},
		anchor: 'end',
		align: 'end'
	}
}
```
Its JSFiddle : https://jsfiddle.net/78ndvf2n/

I'm concerned about the `_meta[0]` though. Is `_meta` likely to have other sub-object than `0`?

**Comment by simonbrunel** [comment]
You should really not access _meta directly, that's very internal and have a special structure. If you want to access dataset metadata, you can use `chart.getDatasetMeta(datasetIndex)`. I'm quite sure there is `ctx.datasetIndex`, if not that's a bug.

**Comment by simonbrunel** [comment]
I think I would first move the summation logic into a separated plugin responsible to compute the total for each "stack" and the utmost dataset index, the one for which you want to display the label. It would happen only one time, before the chart update (better for performances):

```javascript
const totalizer = {
  id: 'totalizer',

  beforeUpdate: chart => {
    let totals = {}
    let utmost = 0

    chart.data.datasets.forEach((dataset, datasetIndex) => {
      if (chart.isDatasetVisible(datasetIndex)) {
        utmost = datasetIndex
        dataset.data.forEach((value, index) => {
          totals[index] = (totals[index] || 0) + value
        })
      }
    })

    chart.$totalizer = {
      totals: totals,
      utmost: utmost
    }
  }
}
```

Then you need to register this plugin to the charts you want to display the total:

```javascript
new Chart('chart', {
  plugins: [totalizer],
  // ...
}
```

At this point, you can access computed information from `chart.$totalizer` and thus configure the datalabels plugin easily:

```javascript
new Chart('chart', {
  plugins: [totalizer],
  options: {
    plugins: {
      datalabels: {
        formatter: (value, ctx) => {
          const total = ctx.chart.$totalizer.totals[ctx.dataIndex]
          return total.toLocaleString('fr-FR', {
            style: 'currency',
            currency: 'EUR'
          })
        },
        display: function(ctx) {
           return ctx.datasetIndex === ctx.chart.$totalizer.utmost
        }
      }
    }
  }
  // ...
}
```

Note that it's better to hide the other labels using the `display` option because nothing else will be computed for this label (e.g. the `formatter` will not be called for hidden labels).

Fiddle: https://jsfiddle.net/simonbrunel/9ezggxx5/

Of course this example doesn't take in account all use cases, such as grouped stacks or negative values, but I think it's a good starting point that should answer your question.

**Comment by LeoDupont** [comment]
I think your solution is much cleaner, so I opted for it. Thank you!
I won't use negative values nor grouped stacks for this project, but it may be a good plugin idea.

PS: I indeed have `ctx.datasetIndex` in the `formatter`, but I could not use it in my previous implementation (with a `datasets.filter(/* ... */)`).

**Comment by simonbrunel** [comment]
Sounds good!

FYI, the `array.filter` callback takes [extra arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) such as the index and the array itself. In your case you would have used `index` as the dataset index:

```javacript
let datasets = ctx.chart.data.datasets.filter(
  (ds, datasetIndex) => ctx.chart.isDatasetVisible(datasetIndex)
)
```

**Comment by ShafighBahamin** [comment]
Hi. I'm new to using Chart js and I wanted to ask how to put the total count of stacked bar chart at the top of each bar.

**Comment by shgithu6** [comment]
Try this for toggle dataset

plugins: {
            datalabels: {
                formatter: (value, ctx) => {
                    if (ctx.datasetIndex == 0)
                        return value + "%";
                    else
                        return "";
                },
                anchor: 'end',
                align: 'end'
            }
        }

**Comment by ShafighBahamin** [comment]
I already figured it out but thanks still!

**Comment by michvllni** [comment]
I know this is an old topic, but I modified Simon's plugin to be usable for grouped stacks. Hope this helps anyone.
```javascript
const totalizer = {
            id: 'totalizer',
            beforeUpdate: function (chart) {
                var totals = [];
                var utmost = {};
                chart.data.datasets.forEach(function (dataset, datasetIndex) {
                    if (chart.isDatasetVisible(datasetIndex)) {
                        var stack = dataset.stack;
                        utmost[stack] = datasetIndex;
                        dataset.data.forEach(function (value, index) {
                            if (totals[index] === undefined) {
                                totals[index] = {};
                            }
                            totals[index][stack] = (totals[index][stack] || 0) + value;
                        })
                    }
                });
                chart.$totalizer = {
                    totals: totals,
                    utmost: utmost
                }
            }
        }
```

The totals are then callable by using `chart.$totalizer.totals[dataIndex][stack]` and the utmost items are callable by using `chart.$totalizer.utmost[stack]`

**Comment by mindphreaked** [comment]
Thanks a lot @michvllni , This helped a lot. Don't forget to use dataIndex and stack as ctx.dataIndex and ctx.stack if u end up in errors.

**Comment by codeofsumit** [comment]
The provided solutions are for same-length datasets only, right?
Because datasets with data like this:  `{x: '2022-01-02', y: 123}` might not be in the correct order, stacked by the time unit (e.g. in months or years), and will have gaps in data.

I'm trying to make it work for that use case but wasn't successful so far.

**Comment by mgug01** [comment]
I am having the same issue as Synchro- and am also trying to do this in react-chartjs-2. Are there any work-arounds?

**Comment by Voldemorten** [comment]
I am just contributing to this incase any one is working with object structured data (`[{x: 'label', y: 10},...]`) I solved the problem like this: 
```
const totalizer = {
  id: 'totalizer',
  
  beforeUpdate: chart => {
      let totals = {};
      let utmost = {};
  
      chart.data.datasets.forEach((dataset, datasetIndex) => {
          if (chart.isDatasetVisible(datasetIndex)) {
              dataset.data.forEach((value, index) => {
                  utmost[value.x] = datasetIndex;
                  totals[value.x] = (totals[value.x] || 0) + value.y;
              })
          }
      })
  
      chart.$totalizer = {
          totals: totals,
          utmost: utmost
      }
  }
}
```
and in the display method: 
```
display: function (ctx) {
    const x = ctx.dataset.data[ctx.dataIndex].x;
    if (ctx.chart.$totalizer.utmost[x] === ctx.datasetIndex) {
        return true;
    };
    return false;
},
```

Hope this helps someone.

**Comment by stef-van-looveren** [comment]
> I know this is an old topic, but I modified Simon's plugin to be usable for grouped stacks. Hope this helps anyone.
> 
> ```js
> const totalizer = {
>             id: 'totalizer',
>             beforeUpdate: function (chart) {
>                 var totals = [];
>                 var utmost = {};
>                 chart.data.datasets.forEach(function (dataset, datasetIndex) {
>                     if (chart.isDatasetVisible(datasetIndex)) {
>                         var stack = dataset.stack;
>                         utmost[stack] = datasetIndex;
>                         dataset.data.forEach(function (value, index) {
>                             if (totals[index] === undefined) {
>                                 totals[index] = {};
>                             }
>                             totals[index][stack] = (totals[index][stack] || 0) + value;
>                         })
>                     }
>                 });
>                 chart.$totalizer = {
>                     totals: totals,
>                     utmost: utmost
>                 }
>             }
>         }
> ```
> 
> The totals are then callable by using `chart.$totalizer.totals[dataIndex][stack]` and the utmost items are callable by using `chart.$totalizer.utmost[stack]`

This is great!! thanks a lot.

**Comment by alundstroem** [comment]
Mb a total thread-gravedigger but I've updated this for the version I happened to use, if anybody else is using ChartJS 3.9.x it might help? See https://jsfiddle.net/v3z5umt0/ [https://github.com/chartjs/chartjs-plugin-datalabels/issues/91](url)
