### ISSUE TITLE
Offset doesn't seem to do anything for horizontal bar

### ISSUE THREAD

**Issue by ihelmer07** [chartjs/chartjs-plugin-datalabels#160]
I'm trying to move the data labels over, specifically to make them look similar to:
![image](https://user-images.githubusercontent.com/14080785/69163611-233fdb80-0ab4-11ea-89be-c645dd7607b0.png)

(with larger font).

Using `align: end` makes the numbers be on the edge of the bar, not _within_ the end of the bar.

`offset` is supposed to work but maybe I'm not correctly formatting the item.

I have two graphs so I can't change the global settings (as one needs labels and one doesn't)

Here is a fiddle - you can change the offset # to be whatever you wish and the labels do not move.
[Link to fiddle recreating the issue](https://jsfiddle.net/zy269wb5/)

Fiddle has clamp and padding because I was trying this to see if they worked. They can be removed as they don't have an effect.

**Comment by simonbrunel** [comment]
Hi @ihelmer07! Sorry for the late reply. I hope you figured out how to implement that use case but if not, I think you need to use: `{ anchor: 'end', align: 'start' }`. This will move the label inside the bar (see [fiddle](https://jsfiddle.net/z7mxaj6q/)) and then you can use `offset` to add some margin between the label and the bar right border.

Note that [`offset` doesn't have effect if `align: 'center'`](https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html#alignment-and-offset), which is the default.
