### ISSUE TITLE
Unexpected token error during install

### ISSUE THREAD

**Issue by cdecinkoKnight** [chartjs/chartjs-plugin-datalabels#163]
Unable to install via NPM.  Getting this error every time, even after restarting VS Code.

    Unexpected token < in JSON at position 124744 while parsing near '...ALsNVbGg==",

16 silly saveTree `-- vuex@3.1.2
17 verbose stack SyntaxError: Unexpected token < in JSON at position 124744 while parsing near '...ALsNVbGg==",
17 verbose stack       <<
17 verbose stack       << << < HE...'
17 verbose stack     at JSON.parse (<anonymous>)

**Comment by simonbrunel** [comment]
It works for me, that may be related to your project setup. Unfortunately, I can't get any clue from the content of your message so will close this ticket but feel free to re-open with more context.

```sh
# npm install chartjs-plugin-datalabels

...

+ chartjs-plugin-datalabels@0.7.0
added 1 package and audited 1 package in 1.806s
found 0 vulnerabilities
```
