### ISSUE TITLE
anchor: 'start' does not position correctly when starting tick is not zero

### ISSUE THREAD

**Issue by charlesprescottcollins** [chartjs/chartjs-plugin-datalabels#164]
Chartjs sometimes changes the starting tick value of a linear cartesian axis so that it is not zero.  When this occurs the position of the datalabels is not calculated correctly and can cause the datalabel to appear off the canvas (when anchor is 'start') or off center (when anchor is 'center').

**Steps to reproduce:**
1. Visit https://jsfiddle.net/cpciv/j59ahgwn/
2. resize the browser window from very small width to a larger width

**Expected result**
1. Data label would appear at the start of the bar
2. Data label would remain at start of the bar across all browser window widths
3. Data label would not move off the left of the chart, bar, and canvas

**Actual result**
1. At small browser window sizes where the starting tick is zero, the data label is positioned correctly
2. At larger browser window sizes where the starting tick is not zero, the data label moves either partially or completely out of view
3. The data label appears anchored to the zero tick mark which may be hidden and appears shifted left of the Y axis line

**Workarounds**
1. set the tick option `beginAtZero: true`  e.g. https://jsfiddle.net/cpciv/1L9nvgyd/
However this is not ideal, not all scales can start at zero and the auto-scaling of the axes can be helpful

**Comment by simonbrunel** [comment]
Hi @charlesprescottcollins! You need to use the [`clamp: true` option](https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html#clamping) introduced in version 0.5.0 (https://jsfiddle.net/0p34geah/).
