### ISSUE TITLE
Pie Chart - Multiple labels with different colors

### ISSUE THREAD

**Issue by brunoricardore** [chartjs/chartjs-plugin-datalabels#168]
I'm trying to use multiple labels, which one use a different color, in a Pie chart, but both got the same color, this is my code:

```js
plugins: {
  datalabels: {
    align: 'end',
    anchor: 'end',
    textAlign: 'center',
    offset: 3,
    color: 'pink',
    labels: {
      value: {},
      title: {
        color: 'blue'
      }
    },
    formatter: (value, ctx) => {
     const label = ctx.chart.data.labels[ctx.dataIndex];
       return [value + '%', label];
     }
  },
}
```

can somebody helpme?

**Comment by JohnArcher** [comment]
Could you create a jsfilddle or codepen, please?

**Comment by simonbrunel** [comment]
@brunoricardore This should work (see [this example](https://github.com/chartjs/chartjs-plugin-datalabels/blob/master/samples/advanced/multiple-labels.html#L90)) if you use a version >= 0.7.0. If you still have issue, please re-open this ticket with a jsfiddle or codepen as suggested by @JohnArcher.
