### ISSUE TITLE
Click event for data labels

### ISSUE THREAD

**Issue by haimich** [chartjs/chartjs-plugin-datalabels#17]
I'd like to include a line chart in my webapp that has similar capabilities as the [Google Annotation Chart](https://developers.google.com/chart/interactive/docs/gallery/annotationchart):

![googlecharts](https://user-images.githubusercontent.com/2170127/33666154-6f9fef30-da99-11e7-9bf9-63e7765da44d.png)

I'd really like to use Chart.js for this but after hours of researching I still don't have a working solution.

The datalabels plugin seems perfect for this but I would need a click handler where I can identify the data point the label belongs to. I tried to listen to Chart.js [events](http://www.chartjs.org/docs/latest/general/interactions/events.html), but when I call `getElementAtEvent(event)` I don't get any results. I guess this has to do with the fact that datalabels is a plugin, so Chart.js can not identify the label.

I also tried to use chartjs-plugin-annotation, which has click handler support. But here I struggle to place the annotation at the correct position. Additionally the box annotations seem to lack the possibility to display a label.

Here is an example to demonstrate my problem: https://jsfiddle.net/w52twy01/

Thanks in advance!

**Comment by simonbrunel** [comment]
You right, labels are not chart elements and I don't think that will change since they will not be taken in account by the chart anyway during interactions. And there is currently no way to retrieve labels that intersects with the mouse cursor :\

I don't know yet what would the a good API (plugin hooks, callbacks, etc.?), I will think about it but that will not be available soon. Actually, that might be complicated to implement because the label position is computed during the draw process, using context2d transformations, so we never really know what is the effective label box coordinates.

**Comment by haimich** [comment]
Thanks for the quick response! I will opt for another solution then for now :)

After some more digging I found that the Highstock flags feature comes very close to what I need: https://www.highcharts.com/stock/demo/flags-general

**Comment by simonbrunel** [comment]
@haimich sorry for the lack of solution, I will keep that ticket open as a remember to implement that feature.

**Comment by pingcheng** [comment]
Any progress on this function, need event handlers in my project too 😄

**Comment by simonbrunel** [comment]
@pingcheng what event(s) do you need?

I'm thinking to implement `click`, `enter` and `leave` as follow:

```javascript
options: {
  plugins: {
    datalabels: {
      listeners: {
        // called for any labels
        enter: function(context) { ... },
        leave: function(context) { ... },
        click: function(context) { ... }
      }
    }
  }
}
```

`listeners` at the dataset level would receive events only for labels of the same dataset :
```javascript
data: {
  datasets: [{
    datalabels: {
      listeners: {
        // called only for labels of the 1st dataset 
        click: function(context) { ... }
    }
  }, {
    // ...
  }]
}
```

The `context` would give everything needed to known what data generates the event (i.e. `context.datasetIndex` and `context.dataIndex`). It would be also possible to alter the `context` in the handlers and thus if a listener explicitly returns true, the associated label would be updated with the new context and the chart re-rendered. That would allow to implement any kind of interaction with labels, for example:

```javascript
datalabels: {
  listeners: {
    // called for any labels
    enter: function(context) {
        context.hovered = true;
        return true;
    },
    leave: function(context) {
        context.hovered = false;
        return true;
    }
  }
  backgroundColor: function(context) {
      return context.hovered ? "blue" : "green";
  }
}
```

What do you guys think?

**Comment by pingcheng** [comment]
hi @simonbrunel, my project need a function like click a figure label on chart to jump to another page to display a detail chart. Click event listener would enough to me, if support hover event also would be sweet! 👍 

Thanks!

**Comment by simonbrunel** [comment]
A first implementation is ready to be merged, @pingcheng @haimich can you please checkout #40 and confirm that it works with your use cases. Fee free to review the code and leave comments if needed :)
