### ISSUE TITLE
Font Awesome 5 fonts

### ISSUE THREAD

**Issue by josephbridgwaterrowe** [chartjs/chartjs-plugin-datalabels#170]
I'm trying to use the Font Awesome 5 Free fonts with this plugin without much success.

I have forked the solution from @simonbrunel (#25, thank you) and made some changes that I thought should work for the newer version of Font Awesome. Changing the font family and using the 5.0.1 CSS file from FA (https://use.fontawesome.com/releases/v5.0.1/css/all.css).

Here is my jsfiddle: https://jsfiddle.net/Lr6fqbu3/2/

But I'm left with boxes instead of the FA icons:

![2020-02-18_08-15-03](https://user-images.githubusercontent.com/1495123/74754759-f6bc6c80-5226-11ea-8454-a6a3ce9d286a.png)

Any help would be appreciated as I'm struggling to find a simple alternative method of applying datalabels to Charts.

Thanks.

---

**UPDATE** Wrapping the font family in double quotes was the magic sauce required:

```
family: '"Font Awesome 5 Free"'
```

![2020-02-18_08-31-49](https://user-images.githubusercontent.com/1495123/74756284-29fffb00-5229-11ea-91ad-9e9753dafd87.png)

**Comment by josephbridgwaterrowe** [comment]
Closing issue as I solved it myself after reviewing the datalabels source code... I hope this helps someone else who missed this requirement.

**Comment by lorrisbaum** [comment]
Hello, neither of the two jsfiddle seems to work? Do you have a solution? Thank you so much :)

**Comment by josephbridgwaterrowe** [comment]
Hi @lorrisbaum,

I'm not sure why its not working at present, and unfortunately this is code that I no longer use.

However, I will take a look at it when I get some time this week (maybe today) and let you know how it goes.
