### ISSUE TITLE
Formater function gives artifact

### ISSUE THREAD

**Issue by Tadek888** [chartjs/chartjs-plugin-datalabels#173]
```js
plugins: {
	datalabels: {
		anchor: 'end',
		align: 'top',
		formatter: function(value) {
			return value + " aaaaa";
		},
		font: {
			weight: 'bold'
		}
	}
}
```

When I add string to value i get artifact on the top of y scale. 
You can see it on image.

![artifact](https://user-images.githubusercontent.com/9328016/77144861-40e37880-6a87-11ea-834b-18c8ce64ff78.jpg)

Maybe you have some solution.

**Comment by simonbrunel** [comment]
Duplicated of #135, use:

```js
formatter: function(value) {
  return value !== null && value !== undefined ? value + " aaaaa" : null;
},
```
