### ISSUE TITLE
How to set two different font size for each label

### ISSUE THREAD

**Issue by puneeth-91** [chartjs/chartjs-plugin-datalabels#175]
I want to set two different font size for each label. e.g. In my chart I want to show label and value for each bar where both value and label have different font size. Please refer the attached image

![screen-new](https://user-images.githubusercontent.com/57911349/77858849-b1c32700-7223-11ea-9cf9-0551cc3d3fe2.PNG)

I want to set different font size for fruit name and different font size for value using data labels.
Please help with this.

**Comment by simonbrunel** [comment]
You need can use [multiple labels](https://chartjs-plugin-datalabels.netlify.app/guide/labels.html#multiple-labels) to achieve this, something like:

```js
datalabels: {
  labels: {
    fruit_name: {
      font: {
        size: 24
      }
    },
    fruit_value: {
     font: {
        size: 18
      }
    }
  }
}
```
