### ISSUE TITLE
Multiple Custom Labels for each data set.

### ISSUE THREAD

**Issue by SHASHWATAA** [chartjs/chartjs-plugin-datalabels#176]
Is there a way to have an array of labels for each data set?

I tried setting multiple labels as stated [here](https://chartjs-plugin-datalabels.netlify.com/guide/labels.html#multiple-labels) and then removing the unwanted label as stated [here](https://chartjs-plugin-datalabels.netlify.com/guide/labels.html#removing-label)

but i just get "[object Object]" for each label

**Comment by simonbrunel** [comment]
Hi @SHASHWATAA! Please provide a codepen or jsfiddle that reproduces your issue.

**Comment by simonbrunel** [comment]
Closing since no test case has been provided. Feel free to reopen with a way to reproduce your issue.
