### ISSUE TITLE
unable to get display data labels on segments.

### ISSUE THREAD

**Issue by nuznad** [chartjs/chartjs-plugin-datalabels#177]
Dear
I try my best to get display data labels on segments but fail. Kindly help me

[crm_component_html.txt](https://github.com/chartjs/chartjs-plugin-datalabels/files/4502629/crm_component_html.txt)
[crm_component_ts.txt](https://github.com/chartjs/chartjs-plugin-datalabels/files/4502630/crm_component_ts.txt)

**Comment by simonbrunel** [comment]
Plugins options should be declared under `options.plugins.datalabels` but not `options.plugins.chartdatalabels`.
