### ISSUE TITLE
Custom datalabel show on top left corner

### ISSUE THREAD

**Issue by p-drolima** [chartjs/chartjs-plugin-datalabels#179]
Hi,

Having an issue that been flagged before but could not find resolution.

So once I use formatter to create a custom output for values that are not numeric, the output goes outside the bar inline and shows on top left corner.

Can you please let me know if this is an issue related to your plugin or to chart.js? Also, if someone has a solution would be greatful.

Thank you,

Pedro

**Comment by simonbrunel** [comment]
Duplicated of #135, you need to check if value is `null`/`undefined` and return `null` if that's the case:

```js
formatter: function(value) {
  return value !== null && value !== undefined ? value + "%" : null;
},
```
