### ISSUE TITLE
npm not installing this dependency

### ISSUE THREAD

**Issue by johnmerced** [chartjs/chartjs-plugin-datalabels#18]
I'm getting the following messaged when doing npm install:

    > 2017-12-07T13:59:43.6102420Z npm http fetch GET 200 https://registry.npmjs.org/chartjs-plugin-datalabels 125ms
    > 2017-12-07T13:59:43.6102420Z npm sill pacote range manifest for chartjs-plugin-datalabels@^0.1.0 fetched in 157ms

dependencies:
```json 
{
  "axios": "^0.17.1",
  "bulma": "^0.6.1",
  "moment": "^2.19.2",
  "vue": "^2.5.4",
  "vue-router": "^3.0.1",
  "chart.js": "^2.7.1",
  "chartjs-plugin-datalabels": "^0.1.0"
}
```

Any idea what I may be missing?

> Edit(SB): code formatting

**Comment by simonbrunel** [comment]
I just tried to install the npm package and it works, so might be something with your environment. Is it the only dependency that fails? Did you try to `npm cache clean`, then `npm install` to see if that's not a cache issue?

**Comment by johnmerced** [comment]
Yes, I did npm cache clean. And yes, it's installing correctly on my local machine but the server machine is the one giving me the error.

Does the node version might be an issue? I think I have a different node version from the server machine.

**Comment by simonbrunel** [comment]
I'm using npm 5.5.1. I'm not sure how I can help since it seems specific to your server config (maybe a proxy issue as describe in npm/npm#13729). As suggested in [this comment](/npm/npm/issues/13729#issuecomment-241614589), It might help to see the output with `--verbose`.

**Comment by johnmerced** [comment]
Here's the logs, I used `install --save-exact --loglevel silly`
https://pastebin.com/aTwX1Dq3

**Comment by johnmerced** [comment]
I just confirmed and I have the same node and npm version as our server marchine.

**Comment by simonbrunel** [comment]
Based on your logs, it looks like it tries to install only this plugin, are other dependencies (chart.js, vue, moment, etc.) already installed? If so, I would try to install your project from scratch with no pre-existing `node_modules` folder. Then you would know if the issue is specific to that plugin or to all dependencies.

**Comment by johnmerced** [comment]
I fixed it by cleaning the directory completely before doing all the build process.

Thank you for your help!
