### ISSUE TITLE
Compatibility with Chart js 3.0

### ISSUE THREAD

**Issue by sk0gen** [chartjs/chartjs-plugin-datalabels#180]
Do you have any plans to add next version compatibile with Chart.Js@next(3.0)?

**Comment by stockiNail** [comment]
+1

**Comment by stockiNail** [comment]
I'm preparing my app to use Chart.Js 3 but I'm also using datalabels plugin.
Is there any idea when new version (also pre-release in order to test whole app) could be available?
Thanks a lot!

**Comment by benmccann** [comment]
I noticed that `src/utils.js` and `src/label.js` in the `chartjs-next` branch do `import Chart from 'chart.js';`. This is something that `chartjs-chart-financial` currently does as well where [@etimberg suggested it needs to be `import { Chart } from 'chart.js';`](https://github.com/chartjs/chartjs-chart-financial/issues/88#issuecomment-749292286).

**Comment by santam85** [comment]
@benmccann fixed that in #214

**Comment by simonbrunel** [comment]
@santam85 @stockiNail I rebased the `chartjs-next` branch on master and squashed commits in 2 major changes:

- Update to Chart.js v3.0.0-beta.13 (f40336b5c1ae3a97c186bf076fa5fe15a2da0f58)
- Convert the plugin to ESM (04fe725a427a882205b14125c167f8b07098fae7)

Hopefully, I didn't break anything :)

Can you please checkout and test the `chartjs-next` branch so I can release `v2.0.0-beta.1` (probably tomorrow)?

**Comment by stockiNail** [comment]
@simonbrunel rebased! Thank you!

**Comment by santam85** [comment]
@simonbrunel tested successfully in ng2-charts, apart from the legend/tooltip issue you noticed in the docs, everything else seems to check out! Thanks in advance for releasing this!

**Comment by simonbrunel** [comment]
@santam85 did you checkout a clean version of the latest `chartjs-next` branch? the legend/tooltip issue should be fixed.

**Comment by santam85** [comment]
> @santam85 did you checkout a clean version of the latest `chartjs-next` branch? the legend/tooltip issue should be fixed.

You're right, I had a stale instance of vuepress still running, and new ones pick a different port automatically. That's fixed as well!

**Comment by simonbrunel** [comment]
[v2.0.0-beta.1](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v2.0.0-beta.1) is released! 🚀 

I'm closing this issue in favor of #213.
