### ISSUE TITLE
Not work with chartJs 2.9 version it throws an error

### ISSUE THREAD

**Issue by arunreghu** [chartjs/chartjs-plugin-datalabels#186]
Not work with chartJs 2.9 version it throws an error 

errorMessage": "Cannot read property 'x' of null", "errorType": "TypeError", "stackTrace":

**Comment by simonbrunel** [comment]
@arunreghu Can't help without a proper way to reproduce your issue. Please add a codepen link to that ticket that produces this error, then reopen.
