### ISSUE TITLE
Label distance from Bar in Bar Chart

### ISSUE THREAD

**Issue by joao-m-santos** [chartjs/chartjs-plugin-datalabels#19]
Hello, I'm having trouble finding a way to distance the value from the label of a Bar in a vertical Bar chart from the Bar itself. Is this a feature that does not exist, or am I just overlooking something?

Thanks for your attention.

**Comment by simonbrunel** [comment]
I think you are looking for the [`offset` option](https://chartjs-plugin-datalabels.netlify.com/positioning#alignment-and-offset) (which only apply to `align !== 'center'`.

**Comment by joao-m-santos** [comment]
I've tried the offset option but indeed it doesn't work. Here's a simple image showing what I mean:
On the left is what I currently have and on the right is my objective.

![barproblem](https://user-images.githubusercontent.com/31653199/33823437-136c7ab8-de53-11e7-90fe-81285423970e.png)

**Comment by simonbrunel** [comment]
I think your left screenshot uses `align: 'center'`?

This should work:
```javascript
{
    align: 'end',
    offset: 8
}
```

**Comment by joao-m-santos** [comment]
Yes, that was it! Thanks alot ;)
