### ISSUE TITLE
Hide datalabel on a specific bar

### ISSUE THREAD

**Issue by JoaoVictorDaijo** [chartjs/chartjs-plugin-datalabels#190]
I have a graph with multiple values for the 'labels' property, one of them is 'missing'.
![Screenshot from 2020-07-15 17-50-49](https://user-images.githubusercontent.com/33362807/87594799-e4eed080-c6c3-11ea-89ef-4d38e0f34484.png)

In some cases i need to hide this 'missing'. What I do I simply not write 'missing' in the 'labels' parameter nor it's value on the data property. 
But if I do this datalabels writes the 'missing' values over the canvas anyway.
![Screenshot from 2020-07-15 17-48-55](https://user-images.githubusercontent.com/33362807/87595057-59297400-c6c4-11ea-92ef-75fca91ce9cf.png)

I can't use this solution https://github.com/chartjs/chartjs-plugin-datalabels/issues/20#issue-285628568 since this graph only uses a single dataset, so I can't set datalabels display to false based on a dataset.

I think I can solve this using a scriptable option the same way we hide datalabels for 0 values: https://github.com/chartjs/chartjs-plugin-datalabels/issues/6#issue-256921147

But I don't know how I can access a labels specific value. I tried:
```
display: function(context) {
      return context.dataset.data.labels[context.dataIndex] != "missing";
}
```
But it didn't work.

This is how my graph's code looks like:

```
var ctx = document.getElementById('graph_5547');
var myChart = new Chart(ctx, {
	type: 'horizontalBar',
	data: {  labels: [ 'Escutar as crianças','Mapear as necessidades e interesses','Organização das oportunidades de aprendizagens','Organização dos espaços','Organização dos tempos','Organização dos materiais','Organização das interações','Como documentar os percursos de aprendizagens','Previsão de momentos de avaliação','Outros','Não sabe/Não respondeu','missing'],
		datasets: [
			{ 
				maxBarThickness: 45,
                                label: 'Sim',
				backgroundColor: '#9f9cce',
				borderWidth: 0,
				data: [ 12,9,9,11,11,11,9,7,7,1,0,13]
			}]
		},
	options: { 
```

**Comment by gemini86** [comment]
Use the formatter and pass in the context object. You can access the chart labels from there and format the value depending on the label.

````javascript
options: {
    plugins:{
        datalabels: {
            formatter: function(context, value) {
                 return context.chart.config.data.labels[context.dataIndex[i]] == 'missing' ? '' : value;
            }
        }
    }
}
````

**Comment by JoaoVictorDaijo** [comment]
> @JoaoVictorDaijo Use the formatter and pass in the context object. You can access the chart labels from there and format the value depending on the label.
> 
> ```js
> options: {
>     plugins:{
>         datalabels: {
>             formatter: function(context, value) {
>                  return context.chart.config.data.labels[context.dataIndex[i]] == 'missing' ? '' : value;
>             }
>         }
>     }
> }
> ```
> 
> I think though it may be better to write a function to remove the data + label all together before rendering.

Thanks for the reply. I'm mixing PHP and javascript, originally I tried to skip the iterations where I would parse the 'missing' data but it didn't work. I had solved the issue like your suggestion, removing the undesired data.

Anyway now I know how to use the formatter so maybe in the future it will be useful.

**Comment by benzkji** [comment]
if your label has a background color, or a border, you can return  `null` instead of the empty string, so not even an empty background color will be shown. thanks @JoaoVictorDaijo

**Comment by simonbrunel** [comment]
@JoaoVictorDaijo using a scriptable option for `display` should work but there is an error in your original comment.

It should be:
```js
display: function(context) {
      return context.chart.data.labels[context.dataIndex] !== 'missing';
}
```
