### ISSUE TITLE
Change display: 'auto' behavior (it's hiding bigger values and showing the smaller ones)

### ISSUE THREAD

**Issue by JoaoVictorDaijo** [chartjs/chartjs-plugin-datalabels#193]
![image](https://user-images.githubusercontent.com/33362807/88977734-ce846f80-d294-11ea-8c4a-2a12fb02dc98.png)

Is there any way to make display: 'auto' hide numbers for smaller percentages instead of the bigger ones? In the image the yellow/orange slice is 6%. I also had the issue of 0% values (for empty slices) being displayed instead of the other labels when using display 'auto'.

I kind of solved this issue with a scriptable option, With this I display values only for labels > 1 and can use display: 'auto' at the same time;

```
display: function(context) {
         if (context.dataset.data[context.dataIndex] > 1){
		return "auto";
	}
	else{
		return context.dataset.data[context.dataIndex] > 1;
	}
}
```

![image](https://user-images.githubusercontent.com/33362807/88978335-e3adce00-d295-11ea-9eaf-07a7f8fb0bc8.png)

To be sincere I'm not sure how or why it works but this solved the problem for many graphs like the lower one (which displayed the 1% value instead of 4%), but there are cases like the upper graph where there'll be an empty space with no numbers written. 

I could change the function to ignore values > 2 to solve the issue in the first image but I wonder if there is a better solution.

I read in the documentation that I can set the display for individual labels but I have multiple graphs that may change when new data arrives in the following years, so it's not possible to solve this in a fixed way I think.

**Comment by simonbrunel** [comment]
@JoaoVictorDaijo I agree we need a way to implement such use case. Let's use #183 to track this feature request.
