### ISSUE TITLE
Multiline Labels styling

### ISSUE THREAD

**Issue by ronmara** [chartjs/chartjs-plugin-datalabels#198]
I'm trying to style multiline labels, each line with different font-weight. Make the first row bold and the second normal but I didn't found any documentation about styling specific parts of the label, only the whole label

here is my configuration code:

```
{
  datalabels: {
    color: "black",
    anchor: "end",
    textAlign: "center",
    align: "end",
    formatter: function (value, context) {
      return `${value}%\n${context.dataset.label[context.dataIndex]}`;
    },
    font: {
      weight: "bold",
      size: 11,
    },
  },
}
```

and here is my current graph. I want to make the value bold and the description normal:

![image](https://user-images.githubusercontent.com/11742944/95326220-e8e95380-08aa-11eb-81bb-2bc1a77890dd.png)

**Comment by simonbrunel** [comment]
It's not possible to have one label containing text with different styles (similar constrains as #192). Alternatively, you could try to generate 2 labels per data (see [docs](https://chartjs-plugin-datalabels.netlify.app/guide/labels.html#multiple-labels) & [example](https://chartjs-plugin-datalabels.netlify.app/samples/advanced/multiple-labels.html)).
