### ISSUE TITLE
Is it possible to display the Chart's legends inside a stacked horizontal bar graph?

### ISSUE THREAD

**Issue by Kobeboy15** [chartjs/chartjs-plugin-datalabels#199]
I'm currently working on a project that requires me to use a stacked horizontal bar graph, the issue I face now is to display the legends of the chart, but inside each of the different bars is the corresponding legend associated with the bar. It sounds a little confusing to explain, but the picture will make a ton more sense. I'm only able to display the value/data of the bar, but I want the legend to be seen and not the value/data, I'll have the tooltip handle that.

Expected:
![image](https://user-images.githubusercontent.com/23691843/96667641-0844ae00-138c-11eb-80a6-ea1496016b1f.png)

What I have:
![image](https://user-images.githubusercontent.com/23691843/96667688-1db9d800-138c-11eb-8e8a-1b3ebbafe8df.png)

**Comment by kurkle** [comment]
You can format the label to be whatever you want:

https://chartjs-plugin-datalabels.netlify.app/guide/formatting.html#data-transformation

**Comment by Kobeboy15** [comment]
Thanks @kurkle, I was confused reading this the first time, but looking at the docs again, it all stated to make sense. Gonna close now, since the issue has been resolved!
