### ISSUE TITLE
There is no sample to show how to use this plugin

### ISSUE THREAD

**Issue by hlide** [chartjs/chartjs-plugin-datalabels#2]
We all like to catch glimpse of some samples to make up a decision to try a plugin or not. Because, right now, even with the documentation, it is not clear how to use it.

**Comment by simonbrunel** [comment]
I can't agree more, samples are coming! This is a pretty new plugin, still in development, samples wasn't the highest priority.

**Comment by simonbrunel** [comment]
A few samples are now available ([sources](/chartjs/chartjs-plugin-datalabels/tree/master/samples) | [website](https://chartjs-plugin-datalabels.netlify.com/samples/)).

**Comment by hlide** [comment]
Thanks very much

**Comment by simonbrunel** [comment]
Closing since there are now [a few samples](https://chartjs-plugin-datalabels.netlify.com/samples/) to get started.

**Comment by aslam** [comment]
@simonbrunel Will this plugin work with HorizontalBar char type? Can you please add an example with that type?

Thanks in advance.

**Comment by simonbrunel** [comment]
@aslam this plugin works with horizontal bars, exactly the same way as the [vertical ones](https://chartjs-plugin-datalabels.netlify.com/samples/charts/bar.html), only the chart type changes to `horizontalBar`.

**Comment by Cristianopavan** [comment]
hi "https://cdn.jsdelivr.net/npm/chartjs-plugin-piechart-outlabels"  this plugin is not working for 
chart js-funnel chart

**Comment by simonbrunel** [comment]
@Cristianopavan this is not the same plugin, you should report your issue on this [project](https://github.com/Neckster/chartjs-plugin-piechart-outlabels) instead.

**Comment by nuznad** [comment]
Dear 
I try my best to display data values on pie chart segments. Kindly help. My code is attached.
