### ISSUE TITLE
Angular Charts - Datalabel plugin - Enable (or disable) on specified chart

### ISSUE THREAD

**Issue by voidbrain** [chartjs/chartjs-plugin-datalabels#200]
When I have multiple charts on the page, plugin is registered global so I am not able to  to enable or disable it where needed.

Here is an example:
https://stackblitz.com/edit/angular-chartjs-multiple-charts-k3erus?file=src/app/app.component.ts

How am I supposed to enable the plugin only on one of the charts?

**Comment by damian-mariachi-team** [comment]
You should first plugin unregister in ngAfterViewInit():
`Chart.plugins.unregister( ChartDataLabels );` 

And then you can enable it in single chart...

**Comment by simonbrunel** [comment]
> How am I supposed to enable the plugin only on one of the charts?

https://chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#registration
