### ISSUE TITLE
error TS2665: Invalid module name in augmentation.

### ISSUE THREAD

**Issue by damian-mariachi-team** [chartjs/chartjs-plugin-datalabels#201]
I use **chartjs-plugin-datalabels** - Version: 0.7.0 with **chart.js** - Version: 2.9.3

My Init-Code:
````
import Chart from "chart.js";
import ChartDataLabels from "chartjs-plugin-datalabels";
````

Everything works fine so far.
But during deployment I get the following error:
````
C:/_projects/ ... /node_modules/chartjs-plugin-datalabels/types/index.d.ts(3,16): error TS2665: Invalid module name in augmentation. 
Module 'chart.js' resolves to an untyped module at 'C:/_projects/ ... /node_modules/chart.js/dist/Chart.js', which cannot be augmented.
````
Have you any idea how to fix it?
Thanks.

**Comment by simonbrunel** [comment]
Hard to say without a reproduction case. Could be because you have `@types/chart.js` in your `package.json` in your `devDependencies`, so if during deployment you don't install dev dependencies, then the chart.js types are missing.

**Comment by damian-mariachi-team** [comment]
Hi Simon!
I found the solution:
I actually installed ```@types/chart.js``` later in ```devDependencies``` and now I don't get the error anymore.
Thanks a lot. 

I close the issue.
