### ISSUE TITLE
duplicated can't resolve

### ISSUE THREAD

**Issue by Kiwi-Lin** [chartjs/chartjs-plugin-datalabels#204]
![1605379481849](https://user-images.githubusercontent.com/55834344/99154669-8c205a80-26ec-11eb-85cf-7568ad0fb9a7.jpg)
Sorry,I want to ask how to solve this problem.It is two dataset labels.I have tried to use "display:auto",but it have not changed anything.Please help me , thanks very much.

**Comment by simonbrunel** [comment]
We can't help with a better description of what you are trying to achieve. Please provide more details **and** a codepen that reproduces your issue.

**Comment by Kiwi-Lin** [comment]
Sorry , maybe I make some additions.This picture has two datasets in it , but I only want to display the datalabel of one of them.Sorry, I don't have codepen.If these descriptions can’t make you understand,maybe we can try other ways.
Thank you for your response!!

**Comment by simonbrunel** [comment]
```js
// At the dataset level, using "display: false"

data: {
  datasets: [{
    // ...
  }, {
    // Dataset to hide labels
    datalabels: {
       display: false
    },
  }]
}

// OR - the shorter way: "datalabels: false"

data: {
  datasets: [{
    // ...
  }, {
    // Dataset to hide labels
    datalabels: false,
  }]
}

// OR - using scriptable option:

options: {
  plugins: {
    datalabels: {
      display: ({ datasetIndex }) => datasetIndex === 1
    }
  }
}
```

**Comment by Kiwi-Lin** [comment]
Thanks very much!!
