### ISSUE TITLE
Instructions (temporary) on how to use this plugin with chart.js v3

### ISSUE THREAD

**Issue by alexkuc** [chartjs/chartjs-plugin-datalabels#212]
I was able to get this plugin working with v3 (https://github.com/chartjs/chartjs-plugin-datalabels/issues/180) but for beginners or new comers, this maybe a little difficult or confusing.

I can create a PR to update `README.md`  with brief instructions on how to do that.

If you feel this is something appropriate, I can create a new PR.

**Comment by simonbrunel** [comment]
@alexkuc I'm not sure about the instructions you are thinking of but it should be covered in the docs instead. The [getting-started.md](https://github.com/chartjs/chartjs-plugin-datalabels/blob/chartjs-next/docs/guide/getting-started.md) and [migration.md](https://github.com/chartjs/chartjs-plugin-datalabels/blob/chartjs-next/docs/guide/migration.md) in `chartjs-next` still need to be updated to reflect Chart.js v3 API changes, though it should not be that different from using the plugin against Chart.js v2.

**Comment by alexkuc** [comment]
@simonbrunel

When you open the repository, `README.md` is loaded by default which says:

> Requires Chart.js 2.7.0 or later

Since there is now `v3`, I think it would make more sense to say something like:

> Requires Chart.js 2.7.0 or later (excluding 3.x.x)
> (for more information on supporting v3, see sub-heading below)

And such, there could be a sub-header saying:

> To use this plugin with chart.js (v3), you would need to checkout branch `chartjs-next` and compile the source as currently, it is not available via CDN. To do so, do:
> `git clone git@github.com:chartjs/chartjs-plugin-datalabels.git`
> `cd chartjs-plugin-datalabels`
> `git checkout chartjs-next`
> `npm install`
> `npm run build`

The idea here is to provide a quick mention for new comers as I am sure more seasoned devs would not require such assistance.

**Comment by simonbrunel** [comment]
I agree it's confusing and we need to make clearer that the current published version is not compatible with v3. I'm not expecting new comers to use the `chartjs-next` branch until the first beta version is released, in which case they will use npm / cdn and will not have to deal with building the plugin.

So I would not add these instructions in `README.md` but instead I will:

- Create a new pinned [GH discussion](https://github.com/chartjs/chartjs-plugin-datalabels/discussions) thread about Chart.js v3 with these build instructions + current progress.
- Update `master/README.md` with:

```
Requires Chart.js >= 2.7.0 < 3.x.x (see branch [`chartjs-next`](...) for Chart.js 3).
```

- Rebase and update `chartjs-next/README.md` with:
```
Requires Chart.js >= 3.0.0-beta.7 or later.

Check [this discussion](...) for current progress and extra instructions.
```

Does that make sense?

**Comment by simonbrunel** [comment]
I created #213 since it's good anyway to have an official pinned topic about status of porting this plugin to Chart.js 3, that I can easily update with current progress. I will update the `README.md` root/docs files if my suggestion solves your concerns.

**Comment by alexkuc** [comment]
> I'm not expecting new comers to use the chartjs-next branch until the first beta version is released, in which case they will use npm / cdn and will not have to deal with building the plugin.

Oh! Didn't realize it is at alpha stage. If it is too early, then I agree, it should not be released otherwise it can cause confusion.

> Does that make sense?

Yeah, totally makes sense. [Chart.js](https://github.com/chartjs/Chart.js) also features a similar description in their README.md (https://github.com/chartjs/Chart.js/issues/8281)

**Comment by alexkuc** [comment]
> I created #213 since it's good anyway to have an official pinned topic about status of porting this plugin to Chart.js 3, that I can easily update with current progress. I will update the README.md root/docs files if my suggestion solves your concerns.

Yeah, this is perfect! I think the issue can be marked as resolved?

**Comment by simonbrunel** [comment]
Thanks @alexkuc for your suggestion and feedback. I updated `master` and will update `chartjs-next` with the docs soon. I'm closing this issue since we have the discussion and another ticket to track this work.
