### ISSUE TITLE
How can I show the label on the point of the line.

### ISSUE THREAD

**Issue by pakorn33** [chartjs/chartjs-plugin-datalabels#216]
How can I show the label on the point of the line. I am using a bar chart and it works properly, but the line is not correct.
I wondered for a time what part of the code was wrong.

The code and picture show below.

Thank you.

![label1](https://user-images.githubusercontent.com/47946379/105122424-c4874f00-5b08-11eb-8384-ff7c0d876cd5.png)
![label2](https://user-images.githubusercontent.com/47946379/105122428-c5b87c00-5b08-11eb-8387-9c0cdfc523a5.png)

`
    
    <script src="plugins/chart.js/Chart.min.js"></script>
    <script type="module" src="plugins/chart.js/chartjs-plugin-datalabels.min.js"></script>

                        $('#barChart').remove(); // this is my <canvas> element
                        $('#barChart_main').append('<canvas id="barChart" style="min-height: 600px; height: 600px; max-height: 600px; max-width: 100%; display: block; width: 644px;" width="515" height="200" class="chartjs-render-monitor"></canvas>');
                           
                        var barChartCanvas = $('#barChart').get(0).getContext('2d');
                        var barChartData = jQuery.extend(true, {}, productionMain);

                        var barChartOptions = {
                            responsive: true,
                            maintainAspectRatio: false,
                            datasetFill: false,
                            tooltips: {
                                titleFontSize: 22,
                                bodyFontSize: 20
                            },
                            scales: {
                                xAxes: [{
                                    scaleLabel: {
                                        display: true,
                                        labelString: 'เวลา'
                                        , fontSize: 20
                                    }, ticks: { fontSize: 20, fontColor: '#000', fontStyle: '500' }
                                }],
                                yAxes: [{
                                    scaleLabel: {
                                        display: true
                                        , fontSize: 20
                                    }, ticks: { fontSize: 20, fontColor: '#000', fontStyle: '500' }
                                }]
                            },
                            title: {
                                display: true,
                                fontSize: 22
                            },
                            legend: {
                                display: true,
                                labels: {
                                    fontSize: 16,
                                    padding: 16
                                }
                            },
                            plugins: {
                                datalabels: {
                                    anchor: 'end',
                                    align: 'end',
                                    rotation: -45
                                }
                            }
                        }

                        var barmain1 = new Chart(barChartCanvas, {
                            plugins: ChartDataLabels,
                            type: graphtype,
                            data: barChartData,
                            options: barChartOptions
                        })

                        barmain1.data.datasets[bb].data.push(result3.list[k]);

                        barmain1.options.title.text = sum;
                        barmain1.options.titleFontSize = '30';
                        barmain1.update();

                 Chart.plugins.unregister(ChartDataLabels);
                 Chart.defaults.global.defaultFontSize = 14;
                 Chart.defaults.global.defaultFontColor = 'black';
                 Chart.defaults.global.defaultFontFamily = "Arial";

                 Chart.Legend.prototype.afterFit = function () {
                     this.height = this.height + 40;
                 };

`

**Comment by simonbrunel** [comment]
Closing in favor of the discussion #215 you also opened.
