### ISSUE TITLE
Get the current StepSize

### ISSUE THREAD

**Issue by eduayme** [chartjs/chartjs-plugin-datalabels#223]
Hi! 

I have this case:
![Captura de pantalla 2021-02-23 a las 13 01 39 (2)](https://user-images.githubusercontent.com/26260104/108840996-63efa400-75d7-11eb-9b72-8d1ffd644282.png)

I am trying to get the current stepSize so I can round the max tick to the next stepSize after my biggest number. I would suggest to be able to consult the stepSize in the options. In my case in the example above I would love to be able to do `Chart.options.stepSize = X` so I can set the max to 2600.

**Comment by eduayme** [comment]
I have tried `console.log(myChart.scales['y-axis-0'].ticksAsNumbers);` and`console.log(myChart.scales['x-axis-0'].ticksAsNumbers);`. This only works with the option `ticks: { beginAtZero: true }`. With this in a false state it seems it is not possible to get them.

**Comment by simonbrunel** [comment]
@eduayme I don't think this is related to this plugin but rather to the [core library](https://github.com/chartjs/Chart.js). Though, it's already possible to set the `stepSize` in options ([docs](https://www.chartjs.org/docs/latest/axes/cartesian/linear.html#step-size)) but you want to set the `max` (or `suggestedMax`?) to your horizontal scale ([docs](https://www.chartjs.org/docs/latest/axes/cartesian/#tick-configuration)) instead.
