### ISSUE TITLE
Remove zero value sector in pie chart

### ISSUE THREAD

**Issue by AlexeyPavlyuck** [chartjs/chartjs-plugin-datalabels#225]
Hi! Please help: how remove zero value sector in pie chart. 
In data: [12,0,0];
version: 2.9.4
<img width="120" alt="Снимок экрана 2021-03-05 в 18 52 52" src="https://user-images.githubusercontent.com/63820958/110147424-51017e80-7de4-11eb-800c-d332a29f6744.png">

**Comment by simonbrunel** [comment]
Hi @AlexeyPavlyuck! See https://github.com/chartjs/chartjs-plugin-datalabels/issues/6

Please, don't use issues for asking questions but instead use either [StackOverflow](https://stackoverflow.com/) or the [discussions section](https://github.com/chartjs/chartjs-plugin-datalabels/discussions).
