### ISSUE TITLE
How to show values pointing pie charts

### ISSUE THREAD

**Issue by vishalbiradar** [chartjs/chartjs-plugin-datalabels#227]
I am using chartjs to create pie charts in my angular application.
So wanted to know is there a way to add the values in the pie chart pointing the respective slices in pie chart or the donut charts.
So that no need to going for mouseover to know the value hold by the each an every slice.
It will give the overall summary by looking at the chart itself.

Please refer the below screenshot.

<img width="638" alt="Screenshot 2021-03-10 at 6 37 56 PM" src="https://user-images.githubusercontent.com/29951629/110634330-da8fc280-81cf-11eb-9595-07486580715c.png">

**Comment by simonbrunel** [comment]
This feature has already been requested (#131) and is still not implemented.
