### ISSUE TITLE
Uncaught TypeError: model.positioner is not a function

### ISSUE THREAD

**Issue by sreejithqb** [chartjs/chartjs-plugin-datalabels#23]
Hello thank you for your plugin and latest update. 
We have a small problem from 0.2.0 update, after the update we are getting the error and labels are missing from the chart. 

**
>>  Uncaught TypeError: model.positioner is not a function
> >  Uncaught TypeError: model.positioner is not a function
> >     at coordinates (chartjs-plugin-datalabels.js:359)
> >     at Object.afterDatasetDraw (chartjs-plugin-datalabels.js:618)
> >     at Object.notify (Chart.min.js:10)
> >     at t.drawDataset (Chart.min.js:10)
> >     at t.drawDatasets (Chart.min.js:10)
> >     at t.draw (Chart.min.js:10)
> >     at t.render (Chart.min.js:10)
> >     at Object.callback (Chart.min.js:10)
> >     at Object.advance (Chart.min.js:10)
> >     at Object.startDigest (Chart.min.js:10)
> >     at Chart.min.js:10
**

**Comment by simonbrunel** [comment]
Hi @sreejithqb, sorry for that. Can you build a jsfiddle that reproduces this issue and/or share the page that doesn't work anymore?

**Comment by simonbrunel** [comment]
From your stack trace, it doesn't seem to match 0.2.0:
- `at coordinates`: [v0.2.0/chartjs-plugin-datalabels.js:359](/chartjs/chartjs-plugin-datalabels/blob/v0.2.0/dist/chartjs-plugin-datalabels.js#L359)
- `at Object.afterDatasetDraw`: [v0.2.0/chartjs-plugin-datalabels.js:618](/chartjs/chartjs-plugin-datalabels/blob/v0.2.0/dist/chartjs-plugin-datalabels.js#L618)

But still 0.1.0:
- [v0.1.0/chartjs-plugin-datalabels.js:359](/chartjs/chartjs-plugin-datalabels/blob/v0.1.0/dist/chartjs-plugin-datalabels.js#L359)
- [v0.1.0/chartjs-plugin-datalabels.js:618](/chartjs/chartjs-plugin-datalabels/blob/v0.1.0/dist/chartjs-plugin-datalabels.js#L618)

**Comment by sreejithqb** [comment]
Ok. So https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels will not pull the latest version?

**Comment by simonbrunel** [comment]
https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels pulls the latest version *if it's not cached by the browser* but it's definitely not a good practice as [warned in the docs](https://chartjs-plugin-datalabels.netlify.com/installation#cdn) and in the [jsDelivr docs](https://www.jsdelivr.com/features):
> Requesting the latest version (as opposed to "latest major" or "latest minor") is dangerous because major versions usually come with breaking changes. Only do this if you really know what you are doing.

There is nothing we can do on our side, I think clearing your cache will fix the issue. I would recommend you to always use a versioned URL in your project in production environments:

https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.2.0

**Comment by simonbrunel** [comment]
Though, I don't understand why you get this error because even if it still uses 0.1.0 (cached), it should work. But I can't investigate further without a test case that reproduces that issue.

**Comment by sreejithqb** [comment]
Thanks Simon. We will check the issue in detail. We are using Angle Theme for Angle. I Think it is a cache issue

**Comment by simonbrunel** [comment]
@sreejithqb did you figure out what was the issue?

**Comment by sreejithqb** [comment]
Yes Simon. That was an issue with Angle theme caching. Resolved the issue.
Thanks for your help. I am closing this issue
