### ISSUE TITLE
The label on the sectors is only displayed after a mouse-over

### ISSUE THREAD

**Issue by Homand-Cindy** [chartjs/chartjs-plugin-datalabels#233]
The label on the sectors is only displayed after a mouse-over.
When loading, only a few labels are displayed. 
After hovering the mouse over the graph, all labels appear.

On loading:
![image](https://user-images.githubusercontent.com/77381122/114512293-3fa85f00-9c39-11eb-9b2e-f0a1cfd9ac5e.png)

After mouse hover:
![image](https://user-images.githubusercontent.com/77381122/114512420-649cd200-9c39-11eb-8081-359929832d5d.png)

**Comment by simonbrunel** [comment]
Please provide us a way to reproduce your issue.

**Comment by Homand-Cindy** [comment]
please find attached a model
[bug.zip](https://github.com/chartjs/chartjs-plugin-datalabels/files/6302446/bug.zip)

I only have the problem if I set the "display" option to "auto".

**Comment by dmitriyq** [comment]
same issue here, if disable animation this would be work as expected
`
       animation: {
          duration: 0
        }
`

**Comment by simonbrunel** [comment]
Thank you @Homand-Cindy for the reproduction case, it's indeed a bug in v2 introduced by #203.

**Comment by simonbrunel** [comment]
@Homand-Cindy @dmitriyq I released a fix (f0b8ca138787c5c0843f1eb9e8715201be72bdee) in [`v2.0.0-rc`](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v2.0.0-rc), can you please confirm that it now works as expected for you?
