### ISSUE TITLE
chart.js v3.1 and chartjs-plugin-datalabels 2.0.0 - Sample

### ISSUE THREAD

**Issue by fly74** [chartjs/chartjs-plugin-datalabels#234]
Hi there, has someone a working example chart.js v3.1 and chartjs-plugin-datalabels 2.0.0. I can't get it work.

**Comment by simonbrunel** [comment]
@fly74 Please provide us a way to reproduce your issue.

**Comment by fly74** [comment]
I tried this one 

https://chartjs-plugin-datalabels.netlify.app/samples/charts/bar.html

With the new libraries.

**Comment by simonbrunel** [comment]
You will have to explain way more in details what you already tried and which errors you get but also **provide a codepen or jsfiddle that reproduces yours issues**.  If you are not reporting an issue, I will convert this ticket to discussion.

**Comment by fly74** [comment]
I put the codes from the link in last post to one js file and used it in the html-main-file like this:

...
<table>
        <tr>
        <td colspan="2">
                                <div class="chart-container1">
                                <canvas id="mycanvas9"></canvas>
                                </div>
        
                        
                        <script type="text/javascript" src="js/jquery.min.js"></script>
                        <script type="text/javascript" src="js/chart.min.js"></script>
                        <script type="text/javascript" src="new.js"></script>
        </td>
...

there no output, shows an empty page. But we can turn to discussion, I know it's all new.

**Comment by fly74** [comment]
I got lables with this, but how to configure it, colors etc.?

`success: function (data) {

			var a = [];
			var b = [];

			for (var i in data) {
				a.push(data[i].a);
				b.push(data[i].b);
			}

			var chartdata = {
				labels: a,
				datasets: [
					{
						backgroundColor: ["#0074D9"],
						data: b,
					}
				]
			};

			var ctx = $("#mycanvas");
			var LineGraph = new Chart(ctx, {
				type: 'bar',
				data: chartdata,
				//---------------------------------------------
				plugins: [ChartDataLabels]
				//---------------------------------------------
			}
			);
		},
		error: function (data) {
		}`

**Comment by simonbrunel** [comment]
You can probably read the documentation about [configuration](https://next--chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#configuration) and [options](https://next--chartjs-plugin-datalabels.netlify.app/guide/options.html#scriptable-options). 

I'm going to close this issue. If you need further support, please use the [discussions](https://github.com/chartjs/chartjs-plugin-datalabels/discussions) instead.
