### ISSUE TITLE
Unable to get labels to always display for points on Area Range Chart

### ISSUE THREAD

**Issue by roysurles** [chartjs/chartjs-plugin-datalabels#235]
Using Chart.js 3.1.0 & current latest of chartjs-plugin-datalabels.

Unable to get labels to always display for points on Area Range Chart.  Ideally, we just need the label for the green middle point to display always.  

Attached zip file containing index.html with source.

![image](https://user-images.githubusercontent.com/37274814/115555646-5a03bd80-a275-11eb-9fe7-b50dddacc3e3.png)

[index.zip](https://github.com/chartjs/chartjs-plugin-datalabels/files/6350844/index.zip)

**Comment by simonbrunel** [comment]
For Chart.js 3.x, you need to use version 2 of this plugin, which is currently in beta:

```js
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0-beta.1"></script>

// or

<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@next"></script>
```

**Comment by simonbrunel** [comment]
Also, don't forget to [explicitly register](https://next--chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#registration) the plugin before creating a chart:

```js
Chart.register(ChartDataLabels);
```
