### ISSUE TITLE
Start AND End Anchor for a Floating Bar Chart.

### ISSUE THREAD

**Issue by Aliervo** [chartjs/chartjs-plugin-datalabels#238]
Unless I am reading the docs wrong, there are only three options for anchoring the data labels: center, start, and end.

I am making a few floating bar charts where I would like the start and end points labeled, but I can't figure out how to position the labels individually; they are always stacked on top of each other.  I am basically just looking for a combination of the start and end anchors, one for each respective point.  

Did I miss something, or does this feature not currently exist?

**Comment by stockiNail** [comment]
@Aliervo do you need something like the following?

![fbAnddatalabels](https://user-images.githubusercontent.com/11741250/115849168-e86a7180-a424-11eb-867e-eaf575cec35c.png)
