### ISSUE TITLE
Displaying custom labels from an array

### ISSUE THREAD

**Issue by boriskogan81** [chartjs/chartjs-plugin-datalabels#24]
I've got an array of data points, and another one of data label strings. I'm graphing the points and would like to use the strings as labels. How do I use this plugin to do so? Here's what I've got right now:

```javascript
datasets: [{
  label: 'Phenological States',
  data: phenoArray(historicalData).values,
  datalabels: phenoArray(historicalData).labels,
  // ...
}]
```

> **Edit(SB)**: code formatting

**Comment by simonbrunel** [comment]
It's possible, but `dataset.datalabels` is reserved for the [plugin options](https://chartjs-plugin-datalabels.netlify.com/options) so can't be used to store custom labels. You can either use the Chart.js [built-in `data.labels`](http://www.chartjs.org/docs/latest/axes/cartesian/category.html#category-axis-definition) (category scale) or you can store them under whatever other unreserved name in the dataset (e.g. `dataset.labels`). Then you need to define a [custom formatter](https://chartjs-plugin-datalabels.netlify.com/formatting.html#data-transformation) and use [context](https://chartjs-plugin-datalabels.netlify.com/options.html#option-context) to reach your values.

If you use `data.labels` ([fiddle](https://jsfiddle.net/simonbrunel/5eeemtor/)):

```javascript
new Chart('id', {
  data: {
    labels: phenoArray(historicalData).labels,
    datasets: [{
      label: 'Phenological States',
      data: phenoArray(historicalData).values
    }]
  },
  options: {
    plugins: {
      datalabels: {
        formatter: function(value, context) {
          return context.chart.data.labels[context.dataIndex];
        }
        // ... other options ...
      }
    }
  }
}
```

If you use `dataset.labels` ([fiddle](https://jsfiddle.net/simonbrunel/sxzqwr80/)):

```javascript
formatter: function(value, context) {
  return context.dataset.labels[context.dataIndex];
}
```

**Comment by boriskogan81** [comment]
Thank you. I have many points in my graph-is there a value that I can pass so that only some of them are labeled? Something similar to autoskip and autoskip padding with scale options?

**Comment by simonbrunel** [comment]
There is no such feature built-in, you can build your own logic by scripting the `display` option:

```javascript
options: {
  datalabels: {
    display: function(context) {
       // your logic here, return true to show a label, else false to hide
       // for example: display 1 label every 3 data
       return context.dataIndex % 3;
    }
  }
}
```

Of course it's way more complex to implement something similar to auto-skip. If you think that's a feature that makes sense, you can create a new ticket with a **detailed** description of the requirements **and a jsfiddle** that illustrates your problematic: that will help me to evaluate if we should and how to integrate that feature.

Did my previous comment solves your original issue?

**Comment by simonbrunel** [comment]
I added some [docs](https://master--chartjs-plugin-datalabels.netlify.com/formatting#custom-labels) and [a sample](https://master--chartjs-plugin-datalabels.netlify.com/samples/formatting/custom-labels.html) how to display custom labels (bea5b4be8dd99a4).

**Comment by HenriqueAurelio** [comment]
The link of the sample @simonbrunel is broken :/
