### ISSUE TITLE
微信小程序引用时会报错

### ISSUE THREAD

**Issue by guoshikai** [chartjs/chartjs-plugin-datalabels#240]
在微信小程序中引用，
```
import {Chart} from '../../../utils/chartjs/Chart';
import ChartDataLabels from '../../../utils/chartjs/chartjs-plugin-datalabels';
// var Chart = require('../../../utils/chartjs/Chart');
// var ChartDataLabels = require('../../../utils/chartjs/chartjs-plugin-datalabels.min');
Chart.plugin.register(ChartDataLabels)
```
两种方式都会在引入插件的时候报错
`Error: module "...../chart.js/helpers.js" is not defined`
对应的额chart.js和chartjs-plugin-datalabels v2.0.0-beta.1版本如下
![image](https://user-images.githubusercontent.com/30238674/115991026-f1ac3780-a5f8-11eb-8708-89f448aa9347.png)
![image](https://user-images.githubusercontent.com/30238674/115991014-e1945800-a5f8-11eb-848f-2e7152dfcf34.png)

**Comment by simonbrunel** [comment]
@guoshikai Please write you comment **in English**.

Apparently, you didn't use npm to install these dependencies so you probably need to import the UMD build of Chart.js:

```js
import { Chart } from '<path-to-chart.js-dir>/dist/chart.min.js';
import ChartDataLabels from '<path-to-chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.min.js>';

Chart.register(ChartDataLabels );
```
