### ISSUE TITLE
CDN for version 2.0.0 returning a 404

### ISSUE THREAD

**Issue by HuangStanley050** [chartjs/chartjs-plugin-datalabels#248]
Hi the version 2.0.0 is no found on CDN, just wondering if  someone can look into this, thank you

![image](https://user-images.githubusercontent.com/33140495/119085621-6bdcaa00-ba47-11eb-8bbc-ca4232ec7123.png)

**Comment by stockiNail** [comment]
@HuangStanley050 version 2.0.0 is not released yet.

There is 2.0.0-rc.1 https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/2.0.0-rc.1/chartjs-plugin-datalabels.min.js

**Comment by simonbrunel** [comment]
Version 2.0.0 has been released ([jsdelivr](https://www.jsdelivr.com/package/npm/chartjs-plugin-datalabels?version=2.0.0))
