### ISSUE TITLE
Clip datalabels by displayed points

### ISSUE THREAD

**Issue by joshkel** [chartjs/chartjs-plugin-datalabels#255]
While playing around with chartjs-plugin-zoom and chartjs-plugin-datalabels, I noticed that datalabels doesn't clip to the chart area; point labels are visible even if the points that they're labeling are off the chart.

Demo: https://codesandbox.io/s/chartjs-datalabels-off-chart-zuyfc?file=/src/index.ts

**Comment by simonbrunel** [comment]
I think you are looking for [`clip: true`](https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html#clipping)?

**Comment by joshkel** [comment]
Thanks; I should have read the docs more closely. Sorry for the trouble.
