### ISSUE TITLE
Extend is not a function

### ISSUE THREAD

**Issue by ukandrewc** [chartjs/chartjs-plugin-datalabels#257]
Getting this error when including h.extend is not a function

**Comment by tomheno** [comment]
I fixed this issue by specifying the version, as `yarn add chartjs-plugin-datalabels` installed the 1.0.0 instead of the latest version, that was needed in my case, as I'm using ChartJs >3.0.0.

Specifying `2.0.0-rc.1`, for example `yarn add chartjs-plugin-datalabels@2.0.0-rc.1` fixed the problem, in my case.

**Comment by ukandrewc** [comment]
@tomheno Sorry, that means nothing to me, I'm just downloading the .js file, but I'll try V1.0.0 and see if that works, thanks.

**Comment by tomheno** [comment]
@ukandrewc Which version of ChartJs are you using ?
If your ChartJs version is `>3.0.0`, you need the `>=2.0.0` version of the plugin, otherwise the `1.0.0` version.

**Comment by ukandrewc** [comment]
@tomheno Thanks, but can only see V1.0.0, don't see any download for V2.0.0, do you have a link?

**Comment by tomheno** [comment]
@ukandrewc I think you need to use the dropdown at the top left corner of the documentation to switch version.
Here is the link for the 2.0.0 documentation, that includes a link to the CDN bundled version (that you need).
https://v2_0_0-rc_1--chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#installation

**Comment by ukandrewc** [comment]
@tomheno Thanks, found the link now - It looks like the guides haven't been updated, both V1 and V2 say V1.0.0

**Comment by ukandrewc** [comment]
@tomheno For the latest version, it says to use  https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels, but that's not been updated to V2. Thansk for your help, appreciated.

**Comment by tomheno** [comment]
@ukandrewc Glad that I could help. 
Actually, it's what I explained in my first message : 

> I fixed this issue by specifying the version, as `yarn add chartjs-plugin-datalabels` installed the 1.0.0 instead of the latest version, that was needed in my case, as I'm using ChartJs >3.0.0.
> 
> Specifying `2.0.0-rc.1`, for example `yarn add chartjs-plugin-datalabels@2.0.0-rc.1` fixed the problem, in my case.
> 
> It's specified for CDN in the doc, not for NPM, so if you are using CDN, you can read it here : https://v2_0_0-rc_1--chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#installation

For the NPM & CDN version, if you want v2.0.0, you have to specify it, it's not a question of link not being updated, it's just that for legacy purpose, they haven't updated the CDN/NPM default version to 2.0.0, it's up to you to load it by specifying it in the CDN link or NPM package version.

**Comment by ukandrewc** [comment]
@tomheno I see that now. It's because I've never used NPM or any CDN. I can see that yarn is a command line, but that's all ;-)

**Comment by ukandrewc** [comment]
@tomheno Thanks for your help, all working now.
