### ISSUE TITLE
Getting dependency error while installing 'chartjs-plugin-datalabels' 

### ISSUE THREAD

**Issue by NandhiniMuthuramalingam** [chartjs/chartjs-plugin-datalabels#258]
Hello All,

How to build a doughnut chart only using chart.js and typescript?

I have the following versions
"chart.js": "^3.3.2" and "@types/chart.js": "^2.9.32".

I am able to display the chart. But I want to achieve the below requirements as well.

Display text inside the doughtnut chart
Display DataLabels in each segment
Need to change the color of hidden legend instead of Strike-Through
I am getting the dependency error when I try to install npm chartjs-plugin-datalabels.

npm ERR! node_modules/chart.js
npm ERR! chart.js@"^3.3.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer chart.js@">= 2.7.0 < 3" from chartjs-plugin-datalabels@1.0.0
npm ERR! node_modules/chartjs-plugin-datalabels

Any suggestion please to resolve this issue?

Thanks!

**Comment by simonbrunel** [comment]
> "chart.js": "^3.3.2" and "@types/chart.js": "^2.9.32".

`@types/chart.js` is for Chart.js 2.x, you need to remove that dependency.

> npm ERR! peer chart.js@">= 2.7.0 < 3" from chartjs-plugin-datalabels@1.0.0

Please install version [2.0.0](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v2.0.0) of this plugin which has been released today.
