### ISSUE TITLE
"undefined" error in the draw section of the plugin

### ISSUE THREAD

**Issue by TheCelebrimbor** [chartjs/chartjs-plugin-datalabels#261]
So I have a dynamic type switching implementation of chart.js. He user can switch between chart types like bar/donut etc.

When the chart is rendered as a Bar chart the very first time, everything is fine. I spent some time tracing the code and this is what happens

1. Chart canvas is created for the very first time
2. `retinaScale()` function of chartjs returns `false`
3. Everything works fine

Now when the type is changed to a Donut,

1. `retinaScale()` returns true which in turn calls the `render()` on the chart.
2.  This invokes the `_drawDatasets` and the `afterDatasetsDraw` hook.
3. This calls the `draw` function of the plugin with labels as undefined and crashed in the for loop 

```
for (i = 0, ilen = labels.length; i < ilen; ++i) {   <-------------- Lables is undefined here.
      label = labels[i];
      state = label.$layout;
```

The funny thing is that this brings down Vuejs altogether, nothing works after.
I think a null check there would solve this issue but I have no idea why this happening in the first place.
This code has been working fine for months, and now today this.

Chartjs version : 3.4.1
Datalabels plugin version : 2.0.0

**Comment by simonbrunel** [comment]
@TheCelebrimbor Can you please provide a minimal Codepen (or similar) that reproduces this issue?

**Comment by TheCelebrimbor** [comment]
@simonbrunel 

Either I am crazy or JavaScript is. The issue is not reproducing now without the null check. It was for 2 days!. Nothing has changed!!. I will close the PR and this issue for now.

Thanks anyway
