### ISSUE TITLE
chart.js/helpers dependency not found

### ISSUE THREAD

**Issue by thespragg** [chartjs/chartjs-plugin-datalabels#264]
Just as the title says, when I try to import the plugin like this:

`import ChartDataLabels from "chartjs-plugin-datalabels";`

It throws the error:

`This dependency was not found:
chart.js/helpers in ./node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.esm.js`

Chart.js was installed using:

`npm install chart,js`

and is using version:

`"chart.js": "^2.9.4",`

**Comment by simonbrunel** [comment]
Either use v1.x of this plugin with Chart.js 2.x or use v2.x of this plugin with Chart.js 3.x.
