### ISSUE TITLE
afterUpdate missing args parameter/too many args passed to layout.prepare()

### ISSUE THREAD

**Issue by mloit** [chartjs/chartjs-plugin-datalabels#266]
While poking around to familiarize myself with the code, I spotted the code below in plugin.js

``` javascript
  afterUpdate: function(chart, options) {
    chart[EXPANDO_KEY]._labels = layout.prepare(
      chart[EXPANDO_KEY]._datasets,
      options);
  },
```
Based on the plugin API documentation, `options` should be the 3rd parameter, following the 'args' parameter.  Luckily this seems to be harmless as `layout.prepare()` is only expecting the `datasets` parameter, so the erroneous one is ignored. 'options' should be removed entirely from the code here.

**Comment by simonbrunel** [comment]
Thanks @mloit for reporting this issue. @LeeLenaleee fixed it in #268, which is merged in master.
