### ISSUE TITLE
The default `offset: 4` option is not working

### ISSUE THREAD

**Issue by ocarreterom** [chartjs/chartjs-plugin-datalabels#285]
This is the result with default `offset: 4`:
<img width="185" alt="Captura de pantalla 2021-10-08 a las 9 56 40" src="https://user-images.githubusercontent.com/11599942/136519621-d9af0f27-92d3-4127-ad4a-0b09bab5464e.png">

With explicit `offset: 4`:
<img width="195" alt="Captura de pantalla 2021-10-08 a las 9 57 06" src="https://user-images.githubusercontent.com/11599942/136519681-c43f462f-e096-4a55-b792-088fefd53cd4.png">

**Comment by stockiNail** [comment]
@simonbrunel @ocarreterom maybe I'm wrong but having a look to the code:

https://github.com/chartjs/chartjs-plugin-datalabels/blob/b04395850bed5729e03e4adb150762819e85898b/src/label.js#L263-L266

I see the `offset` and `padding` are setting to `0` by default but the defaults values are different;

https://github.com/chartjs/chartjs-plugin-datalabels/blob/cdc2e94837a10d19eb1fc86996a271a298821b13/src/defaults.js#L53-L60

I'm expecting:

```javascript
 offset: resolve([config.offset, 4], context, index), 
 ... 
 padding: toPadding(resolve([config.padding, {top: 4, right: 4, bottom: 4, left: 4 }], context, index)), 
```

**Comment by stockiNail** [comment]
@ocarreterom it seems that the sandbox is not available anymore. Is it possible to have it again, in order to do some tests?

**Comment by stockiNail** [comment]
I have done some tests locally and the fallback to 4 sounds working correctly (even if fallback to 0 is weird). If you can provide the example, I can try to go more in deep.

**Comment by ocarreterom** [comment]
@stockiNail I have edited the link https://github.com/chartjs/chartjs-plugin-datalabels/issues/285#issuecomment-938514601

**Comment by stockiNail** [comment]
@ocarreterom having a look to the sample, I see that also `padding` is not applied correctly. And a weird thing is if you register the plugin globally

```javascript
Chart.register(ChartDataLabels);
```

offset and padding are working correctly. I'm having a look to the code because maybe defaults are not applied correctly.

**Comment by stockiNail** [comment]
When you configure the plugin at chart level, without global registration, the defaults are not used. For this reason, as reported comment https://github.com/chartjs/chartjs-plugin-datalabels/issues/285#issuecomment-1143244312, the default value for padding and offset is 0 instead of 4. I think a PR should be submitted.

**Comment by stockiNail** [comment]
PR #325 submitted
