### ISSUE TITLE
Next bar label behind bar in bar chart

### ISSUE THREAD

**Issue by bbtimx** [chartjs/chartjs-plugin-datalabels#29]
Is there any way to prevent this?

![image](https://user-images.githubusercontent.com/4718129/35978068-0473bc68-0ce5-11e8-8b6f-1474d9752ee7.png)

**Comment by simonbrunel** [comment]
@bbtimx I can see different problems in this screenshot, what do you want to prevent exactly?

Please post a jsfiddle that reproduces your issue.

**Comment by bbtimx** [comment]
The red marks are my problems. I add the white stroke to display the same purple color on front of the purple bars but the label seems to be rendered behind the bars.

The blue marks I think is no way to prevent the overlapping.

![image](https://user-images.githubusercontent.com/4718129/35980670-91cdb4a0-0ceb-11e8-8683-73c559f419a1.png)

**Comment by simonbrunel** [comment]
Fixed in 036ddd603c3cad11521ecc188f63add0c917efc6: @bbtimx can you build master and verify that the "red" issue is fixed?

**Comment by bbtimx** [comment]
Thx.
I'll give it a try tomorrow and send you feedback.

**Comment by bbtimx** [comment]
It works like a charm.

Thx a lot.

**Comment by simonbrunel** [comment]
Thanks @bbtimx, will be released in 0.3.0
