### ISSUE TITLE
How to apply this plugin in nuxt.js?

### ISSUE THREAD

**Issue by geofany** [chartjs/chartjs-plugin-datalabels#293]
i got error when apply this

i'm using:
"chartjs-plugin-datalabels": "^1.0.0"
"chart.js": "^2.9.4"
"vue-chartjs": "^3.5.1"

pie.js
![image](https://user-images.githubusercontent.com/37582643/139466582-c80191ad-edd1-4838-82a9-5abd2f18971b.png)

Chart.vue
![image](https://user-images.githubusercontent.com/37582643/139466970-55f08093-2e84-47ac-83fe-53b42985cc1c.png)

error :
![image](https://user-images.githubusercontent.com/37582643/139465910-e17a0860-9706-4d76-92d5-385c748b6ff6.png)

**Comment by simonbrunel** [comment]
Please ask this question to the vue-chartjs repository if you still need support.
