### ISSUE TITLE
not working ver 2.0.0

### ISSUE THREAD

**Issue by ask2rg** [chartjs/chartjs-plugin-datalabels#294]
i don't know why this demo not work i want to show labels on the bar
https://codepen.io/ask2rg/pen/MWvEbRg

**Comment by LeeLenaleee** [comment]
This is because you are not registering the plugin as described in the [documentation](https://chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#integration).

If you do that it works fine

**Comment by ask2rg** [comment]
ohh! my bad, thanks a lot @LeeLenaleee
