### ISSUE TITLE
Uncaught TypeError: e.getDataVisibility is not a function

### ISSUE THREAD

**Issue by amorimlucas** [chartjs/chartjs-plugin-datalabels#299]
Version 1 works great for me, but when I try to use version 2 I get this error:

<img width="527" alt="Screen Shot 2021-11-24 at 10 41 47 AM" src="https://user-images.githubusercontent.com/7674392/143249293-122d84be-6d3e-419e-b03a-09437e40ddf0.png">

This happens with a very basic config. Relevant code: 

<img width="281" alt="Screen Shot 2021-11-24 at 10 46 18 AM" src="https://user-images.githubusercontent.com/7674392/143250007-eda74584-0e74-4116-85f8-867e2c5626fe.png">

**Comment by LeeLenaleee** [comment]
I assume you are using chart.js version 2. You can only use verion 1 of the datalabels plugin with this. Version 2 of the datalabels plugin is for Chart.js v3

**Comment by amorimlucas** [comment]
@LeeLenaleee I'm actually using the very latest Chart.js version (3.7)

**Comment by LeeLenaleee** [comment]
Are you sure you are using Chart.js V3 because there is no version 3.7, latest version is 3.6.

Also if you are sure you are using V3 please provide a working reproducable example of the problem since it seems to be working fine: https://jsfiddle.net/Leelenaleee/6nL5huyz/5/

**Comment by amorimlucas** [comment]
I was using the latest version globally, but an older version locally by mistake. Using the latest version does indeed fix this. Thanks.
