### ISSUE TITLE
Not available on NPM or Bower...

### ISSUE THREAD

**Issue by Sadi-1992** [chartjs/chartjs-plugin-datalabels#3]
I've tried to install this plugin with npm but it returned 404.

https://www.npmjs.com/package/chartjs-plugin-datalabels  -> not found.
https://libraries.io/bower/chartjs-plugin-datalabels -> We can't find whatever it was you were looking for.

**Comment by simonbrunel** [comment]
It's not release yet, waiting for Chart.js 2.7 before a first official release.

**Comment by simonbrunel** [comment]
[Version 0.1.0](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v0.1.0) released (see [documentation](https://chartjs-plugin-datalabels.netlify.com/installation) for links).
