### ISSUE TITLE
Any NaN values shown at the left top corner

### ISSUE THREAD

**Issue by bbtimx** [chartjs/chartjs-plugin-datalabels#30]
If there are any **NaN** values in the data array it will be displayed at the top left corner of the canvas.

![image](https://user-images.githubusercontent.com/4718129/35978323-aded2e82-0ce5-11e8-8407-d00b8bd48d24.png)

Prevent this by adding formatter function:

```
formatter: function(value) {
    if(isNaN(value)){
        return "";
    }
    return value;
}
```

**Comment by simonbrunel** [comment]
There is a bug indeed but I'm not sure the solution is to change the default formatter to check `NaN`.

I will investigate other options.

**Comment by simonbrunel** [comment]
@bbtimx what type of chart generates this issue, can you build a simple jsfiddle that reproduces it?

**Comment by bbtimx** [comment]
@simonbrunel Here is an example: https://jsfiddle.net/7ewmepuv/5/

**Comment by bbtimx** [comment]
@simonbrunel I'm using a mix of different _bar_ and _line_ charts with a function which parse `NULL` values from the database to `NaN` for displaying spanGaps in _line_ charts with `spanGaps: true`. 

So it´s better to not parse `NULL` values to `NaN` in `bar` charts?

**Comment by simonbrunel** [comment]
You need to verify if `null` values are handled the same way as `NaN` for *line* chart (I'm pretty sure it is), and thus `spanGaps` still work with `null`. For *bar* charts, `null` and `NaN` is not handled so I think it's safe to not convert to `NaN`, and let this plugin handle `null` values.

I would still open an issue in the Chart.js project to properly handle `null` and `NaN` bar values.

**Comment by simonbrunel** [comment]
Skipped elements are now correctly handled (1b141f917025403626187f65db546723f0ce635c), though the case of `NaN` in bar charts still need to be fixed in Chart.js and handled the same way as skipped points in line chart.

**Comment by enjik** [comment]
For me, the fix was to check whether the value was null or undefined, and set display in the datalabel config to false.

**Comment by danieloberbillig** [comment]
The only thing that worked for me, was to add checking for NaN as mentioned at the top by bbtimx.
formatter: function (value) {
          return value !== null && value !== undefined **&& !isNaN(value)** ? Math.round(value * 100) + '%' : null;
 },
