### ISSUE TITLE
How to configure in VUE3

### ISSUE THREAD

**Issue by xiaoForest** [chartjs/chartjs-plugin-datalabels#310]
Hi 
How to configure VUe3 Setup after import 

 `
import Vue3ChartJs from "@j-t-mcc/vue3-chartjs";
import ChartJsPluginDataLabels from "chartjs-plugin-datalabels";
export default {
    components: {  Vue3ChartJs, ChartJsPluginDataLabels },
    setup(props, content) {
？？？？？

   }
}
 
`

**Comment by LeeLenaleee** [comment]
First you need to [register](https://chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#registration) it, after that just pass the [options](https://chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#configuration) as normal

**Comment by xiaoForest** [comment]
@LeeLenaleee  Thank you very much, thank you for your pointers.

import Vue3ChartJs from "@j-t-mcc/vue3-chartjs";
import ChartJsPluginDataLabels from "chartjs-plugin-datalabels";
Vue3ChartJs.registerGlobalPlugins([ChartJsPluginDataLabels])
