### ISSUE TITLE
Data Label apply on the all chart

### ISSUE THREAD

**Issue by asmanp2012** [chartjs/chartjs-plugin-datalabels#312]
Hi, I try to make a multi-chart on the same page but Data Label applies on all charts, before registering, just with import that.

**Comment by LeeLenaleee** [comment]
https://stackoverflow.com/a/71884303/8682983

**Comment by asmanp2012** [comment]
> https://stackoverflow.com/a/71884303/8682983

I use web components and it happens before registering. even I put it on the plugins option.

**Comment by LeeLenaleee** [comment]
Datalabels plugin only works after registering so that must be it, otherwise please share a reproducable sample because it will be impossible to help you otherwise

**Comment by asmanp2012** [comment]
> https://stackoverflow.com/a/71884303/8682983
Thank you for your help I use that I fix them.
