### ISSUE TITLE
It is possible to have two line labels in bar charts and the labels will different UI styles

### ISSUE THREAD

**Issue by jefhu** [chartjs/chartjs-plugin-datalabels#33]
Thanks for the great package!

I want to make charts look like this
![image](https://user-images.githubusercontent.com/4658515/36447197-7972117a-1638-11e8-8b48-2a56e2f0350c.png)
As you can see, there two labels and they are in different UI styles.

Please advise

**Comment by simonbrunel** [comment]
It's not possible to have different styles in the same multi-lines label, and I don't think that will be implemented. It's also not (yet?) possible to have 2 labels for the same data. The closest you can get will be something like [this fiddle](https://jsfiddle.net/simonbrunel/nqkzo4cp/).

**Comment by jefhu** [comment]
Thanks Simon! That is good enough!
