### ISSUE TITLE
Need multiple anchor and alignment

### ISSUE THREAD

**Issue by AshwinTayson** [chartjs/chartjs-plugin-datalabels#34]
The library is not able to position the labels properly on a multi-data bar chart. If value of element 1 is 1000 and element 2 is 0, the labels are still floating at the level of 1000.

```
plugins: {
	datalabels: {
		formatter: (value, ctx) => {
			return value !== 0 ? value.toLocaleString(/* ... */) : 'N/A'
		}
		anchor: 'end',
		align: 'end',
		color: '#888'
	}
}
```

![untitled](https://user-images.githubusercontent.com/7329704/36724543-880a61aa-1bd9-11e8-9205-359f4b24cf0b.png)

Expected behaviour: N/A should be on the top of the x-axis origin (0).

**Comment by simonbrunel** [comment]
@AshwinTayson Can you share a jsfiddle that reproduces your issue?

**Comment by simonbrunel** [comment]
@AshwinTayson this work as expected ([fiddle](https://jsfiddle.net/simonbrunel/0jhffwfd/)), your issue looks like you have `stacked: true` on your y axes. Feel free to re-open with a working use case (jsfiddle) that reproduces your issue if still not working for you.
