### ISSUE TITLE
Mixed Chart - Bar label behind line

### ISSUE THREAD

**Issue by JoshAudibert** [chartjs/chartjs-plugin-datalabels#37]
![image](https://user-images.githubusercontent.com/9628374/36861820-0815fc22-1d53-11e8-8b52-47f901ed1b21.png)

I specifically ordered the datasets so that the lines would appear in front of the bars. I was wondering if there was a way to have the bar labels in front of the lines.

**Comment by simonbrunel** [comment]
Duplicates #29 and #32, fixed in [master](/chartjs/chartjs-plugin-datalabels/commit/036ddd603c3cad11521ecc188f63add0c917efc6) and will be released in [0.3.0](/chartjs/chartjs-plugin-datalabels/milestone/3)
