### ISSUE TITLE
dynamic anchor/alignment/offset support

### ISSUE THREAD

**Issue by pingcheng** [chartjs/chartjs-plugin-datalabels#38]
Hi, 

Is there any way to make the anchor/alignment/offset dynamic but fixed? Like make it a callback or something else?

I am setting up the position of labels in the chart but for some cases the position of labels is not perfect, like the 11% in the pic
![screen shot 2018-03-03 at 4 18 06 pm](https://user-images.githubusercontent.com/8447539/36932069-b9176b12-1efe-11e8-951a-c8154b70f9e2.png)

**Comment by simonbrunel** [comment]
You can use [scriptable options](https://chartjs-plugin-datalabels.netlify.com/options#scriptable-options), for example ([jsfiddle](https://jsfiddle.net/simonbrunel/mo5y35yg/)):

```javascript
options: {
  plugins: {
    datalabels: {
      align: function(context) {
        return context.dataset.data[context.dataIndex] < 15 ? 'end' : 'start';
      },
      color: function(context) {
        return context.dataset.data[context.dataIndex] < 15 ? 'black' : 'white';
      }
      // ...
    }
  }
}
```

**Comment by pingcheng** [comment]
thank! It worked

I tried this way, maybe I missed a comma or other mistakes at that time.
