### ISSUE TITLE
typescript error when registering plugin

### ISSUE THREAD

**Issue by nbamfordcirium** [chartjs/chartjs-plugin-datalabels#384]
The following code:

```javascript
import {
  Chart,
} from 'chart.js';
import ChartDataLabels from 'chartjs-plugin-datalabels';
Chart.register([ChartDataLabels]);
```
produces the Typescript error `Property 'id' is missing in type 'typeof import("/Users/bamfordn/airframe-components/node_modules/chartjs-plugin-datalabels/types/index")' but required in type 'ChartComponent'.`

I have the following versions in `package.json`:
```json
 "chart.js": "^4.2.1",
 "chartjs-plugin-datalabels": "^2.2.0",
```

**Comment by MasterCash** [comment]
shouldn't it just be:
```ts
import { Chart } from "chart.js";
import ChartDataLabels from "chartjs-plugin-datalabels";

Chart.register(ChartDataLabels);
```

This is what I am doing in my codebase and it seems to be working.

**Comment by simonbrunel** [comment]
@MasterCash is right, it should be `Chart.register(ChartDataLabels);`

References:
- https://chartjs-plugin-datalabels.netlify.app/guide/getting-started.html#registration
- https://www.chartjs.org/docs/latest/developers/api.html#static-register-chartcomponentlike
