### ISSUE TITLE
TypeError of datalabels in case stacked100 is enabled

### ISSUE THREAD

**Issue by arunfancraze** [chartjs/chartjs-plugin-datalabels#388]
@simonbrunel @y-takey I am facing 1 problem, while writing it in typescript. I am getting a typeError 
`Property 'calculatedData' does not exist on type 'ChartData<keyof ChartTypeRegistry, (number | ScatterDataPoint | BubbleDataPoint | null)[], unknown>'`
You can see the screenshot attached below.
<img width="1440" alt="Screenshot 2023-07-21 at 4 35 54 PM" src="https://github.com/chartjs/chartjs-plugin-datalabels/assets/103022461/88323242-f725-453d-b53f-77180d4ebf83">

_Originally posted by @arunfancraze in https://github.com/chartjs/chartjs-plugin-datalabels/issues/89#issuecomment-1645405415_

**Comment by y-takey** [comment]
@arunfancraze Although I haven't tested it, I think you can achieve a simple solution using the following approach:

```ts
import type { ExtendedChartData } from 'chartjs-plugin-stacked100';

formatter: (value, context) {
  const data = context.dataset.data[context.dataIndex] as ExtendedChartData;
}
```

**Comment by Arun-chaitanya** [comment]
Hi @y-takey, This solution works. You can mark this as closed. Thanks.

**Comment by y-takey** [comment]
Hi @Arun-chaitanya,  Thank you for trying it out! I'm glad it worked and the issue was resolved. :)
but, it seems that I am unable to close it due to insufficient permissions.

**Comment by simonbrunel** [comment]
I would say it's an issue with the `chartjs-plugin-stacked100` package which should probably augment the `ChartData` core type. @y-takey Maybe you could try something like that in your [types.ts](https://github.com/y-takey/chartjs-plugin-stacked100/blob/master/src/types.ts):

```ts
import {ChartData} from 'chart.js';

declare module 'chart.js' {
  interface ChartData< 
    TType extends ChartType = ChartType,
    TData = DefaultDataPoint<TType>,
    TLabel = unknown
  > {
    calculatedData?: number[][];
    originalData?: PluginDataPoint[];
  }
}

// Backward compatibility
export type ExtendedChartData = ChartData; 
```

**Comment by y-takey** [comment]
@simonbrunel Thank you for the advice. I would like to try it when I have some time! :)
