### ISSUE TITLE
Option to give '%' on datalabel

### ISSUE THREAD

**Issue by arnoldgultom** [chartjs/chartjs-plugin-datalabels#39]
data: {
        datasets: [{
            label: 'My Label',
            data: <?php echo json_encode($myData); ?> // contains number like: 77.43, 78.22, etc. I want output like: 77.43%, 78.22%, etc on datalabel
            datalabels: {
                align: 'end',
                anchor: 'end'
            }
        }],

        labels: <?php echo json_encode($myLabel); ?>
    }

I have some codes like that, and I think it will be good if there is an option to give string '%' on each values of datalabel

**Comment by pingcheng** [comment]
add this to your datalabels configuration block
```javascript
formatter: function (value) {
    return value + "%";
}
```

**Comment by arnoldgultom** [comment]
So it is similar with `callback` in `yAxes` option. I see, thanks

**Comment by simonbrunel** [comment]
https://chartjs-plugin-datalabels.netlify.com/formatting

@pingcheng thanks!
