### ISSUE TITLE
helpers.merge is not a function

### ISSUE THREAD

**Issue by Techn1x** [chartjs/chartjs-plugin-datalabels#4]
Getting the following error when loading up my charts;
```
ember-metal.js:3988 TypeError: helpers.merge is not a function
    at configure (chartjs-plugin-datalabels.js:573)
    at Object.afterDatasetUpdate (chartjs-plugin-datalabels.js:581)
    at Object.notify (Chart.js:6937)
    at Chart.updateDataset (Chart.js:4165)
    at Chart.updateDatasets (Chart.js:4140)
    at Chart.update (Chart.js:4087)
    at Chart.construct (Chart.js:3844)
    at new Chart (Chart.js:6340)
    at Class.didInsertElement (ember-chart.js:18)
    at Class.superWrapper [as didInsertElement] (ember-utils.js:423)
```

This occurs on the following line;
https://github.com/chartjs/chartjs-plugin-datalabels/blob/master/src/plugin.js#L304

I am using Chart.js 2.7.0
<img width="437" alt="capture3" src="https://user-images.githubusercontent.com/1049837/30255683-c87c79a6-96e8-11e7-8007-c2d7ce87d8a3.PNG">

When I step through the code, I can see that `helpers` is defined, and has lots of helper functions, but is missing `merge`. It does however have `configMerge` and `scaleMerge` which I believe are more specific use cases of the merge function. Should `merge` perhaps be `configMerge`??

Looking at the other variables on the line, config == {}, options == (default option object), override == undefined.

**Comment by Techn1x** [comment]
In case it helps, here's my options
```
options: {
	maintainAspectRatio: false,	// Set to false for responsive height..... (it's weird)
	responsive: true,
	
	cutoutPercentage: 50,	// Makes this a doughnut graph
	rotation:0.7 * Math.PI,
	circumference:1.6 * Math.PI,
	legend: {
		display: true,
		position: 'bottom'
	},
	plugins: {
		datalabels: {
			backgroundColor: 'black',
			borderColor: 'white',
			borderRadius: 25,
			borderWidth: 2,
			display: true,
			color: 'white',
			font: {
				weight: 'bold'
			},
			anchor: 'start'
		}
	}
}
```

**Comment by simonbrunel** [comment]
@Techn1x it's definitely [`helpers.merge`](/chartjs/Chart.js/blob/master/src/helpers/helpers.core.js#L217) that needs to be used, which is in 2.7.0 and actually works in [the examples](https://chartjs-plugin-datalabels.netlify.com/samples/charts/doughnut.html). When reading your stacktrace, it seems that your are still using 2.6.0 because `Object.notify (Chart.js:6937)` is [2.6](/chartjs/chartjs.github.io/blob/master/dist/2.6.0/Chart.js#L6937), not [2.7](/chartjs/chartjs.github.io/blob/master/dist/2.7.0/Chart.js#L6937).

Maybe a cache / environment issue?

**Comment by Techn1x** [comment]
Thanks, that is good to know and might explain a separate issue I'm having... I'll get back to you when I figure out what's going on.

**Comment by Techn1x** [comment]
Yep, turns out npm & node_modules was lying to me! Despite all of the evidence saying 2.7.0, my website was using chart.js 2.6.0. Wasn't a caching issue, ended up being a chartjs plugin that was importing chartjs in a way that npm didn't recognise

Datalabels are now appearing, with no errors, thanks!
