### ISSUE TITLE
"cc-test-reporter" artefact in npm package

### ISSUE THREAD

**Issue by devjerry** [chartjs/chartjs-plugin-datalabels#46]
In "chartjs-plugin-datalabels" npm package (version 0.2.0 and 0.3.0) there's 12 MB "cc-test-reporter" file.

**Comment by simonbrunel** [comment]
Good catch! We should add it to [.npmignore](/chartjs/chartjs-plugin-datalabels/blob/master/.npmignore) and [.gitignore](/chartjs/chartjs-plugin-datalabels/blob/master/.gitignore).

**Comment by simonbrunel** [comment]
Fixed by 5fd21b8c18f (the package now weights 248KB, 50 files and 9 folders instead of 12.6MB, 132 files and 21 folders).
