### ISSUE TITLE
Using the plugin with JSON

### ISSUE THREAD

**Issue by Doktor-Avalanche** [chartjs/chartjs-plugin-datalabels#48]
Hi, 
I have a captaincasa project that uses chartjs for charts. The chartjs config is passed via json to captaincasa, which is working great.
But is it possible to pass the formatter parameter as JSON. 
I tried different options, but none of them are working.

**captaincasa example** http://www.captaincasademo.com/ccdemos/workplace.workplaceRisc.risc ==> reporting ==> chartjs (in this case no plugins are loaded)

**Comment by Doktor-Avalanche** [comment]
This is the working code. Any idea how to add the formatter?

`JO chart = new JO();
		chart.put("type", "doughnut");

		JO data = new JO();
		chart.put("data", data);
		{
			List<Integer> datasetData = getAantalverkocht();
			List<String> labels = new ArrayList<String>();
			for (int i = 0; i <= 11; i++) {
				labels.add(variables.getDrinkNames().get(i) + " " + datasetData.get(i));
			}
			data.put("labels", labels);

			JOs datasets = new JOs();
			data.put("datasets", datasets);

			JO dataset = new JO();
			datasets.add(dataset);

			JO datadatalabels = new JO();
			datadatalabels.put("align","center");
			datadatalabels.put("anchor","center");
			
			
			dataset.put("data", datasetData);

			List<String> colors = new ArrayList<String>(12);
			colors.add("rgba(166,206,227,1.0)");
			colors.add("rgba(31,120,180,1.0)");
			colors.add("rgba(178,223,138,1.0)");
			colors.add("rgba(51,160,44,1.0)");
			colors.add("rgba(251,154,153,1.0)");
			colors.add("rgba(227,26,28,1.0)");
			colors.add("rgba(253,191,111,1.0)");
			colors.add("rgba(255,127,0,1.0)");
			colors.add("rgba(202,178,214,1.0)");
			colors.add("rgba(106,61,154,1.0)");
			colors.add("rgba(255,255,153,1.0)");
			colors.add("rgba(177,89,40,1.0)");

			dataset.put("backgroundColor", colors);
			dataset.put("datalabels", datadatalabels);

			JO legendlabel = new JO();
			legendlabel.put("fontSize", 30);
			legendlabel.put("fontColor", "#fff");

			JO legend = new JO();
			legend.put("position", "right");
			legend.put("labels", legendlabel);

			JO title = new JO();
			title.put("display", true);
			title.put("fontColor", "#f0f0f0");
			title.put("text", "test");
			title.put("fontSize", 25);

			JO datalabels = new JO();
			datalabels.put("align","center");
			
			datalabels.put("anchor","center");
			
			
			JO font = new JO();
			font.put("weight", "bold");
			font.put("size", "25");
			
			JO datalabels2 = new JO();
			datalabels2.put("color", "#fff");
			datalabels2.put("font", font);
			datalabels2.put("borderWidth", 2);
			datalabels2.put("borderColor", "#000");
			datalabels2.put("borderRadius", "40");
			datalabels2.put("backgroundColor", "#000");
			
			JO plugins = new JO();
			plugins.put("datalabels", datalabels2);
			
			
			JO options = new JO();
			options.put("title", title);
			options.put("legend", legend);
			options.put("plugins", plugins);
			
			

			chart.put("options", options);`

**Comment by simonbrunel** [comment]
[`Function` is not a valid JSON type](https://stackoverflow.com/a/2001471) so it's up to you to implement [protocol to encode / decode function in JSON](https://stackoverflow.com/a/36517369). That's beyond the scope of this plugin and, more generally, Chart.js so you would have better feedback asking this kind of questions on StackOverflow or CaptainCasa directly.
