### ISSUE TITLE
Cant use this plugin with angular-chart.js

### ISSUE THREAD

**Issue by Sadi-1992** [chartjs/chartjs-plugin-datalabels#5]
I'm trying to use this plugin with [angular-chart.js](http://jtblin.github.io/angular-chart.js/) but the datalabels are not showing up.
I've added 

```
plugins: {
          datalabels: {
            color: 'white',
            display: function(context) {
              return context.dataset.data[context.dataIndex] > 15;
            },
            font: {
              weight: 'bold'
            },
            formatter: Math.round
          }
        }
```
to the options using the 'chart-options' directive and `datalabels: {align: 'end', anchor: 'start'}` to the datasets using the 'chart-dataset-override' directive.

But its not working. What am i doing wrong?

**Comment by simonbrunel** [comment]
The syntax looks good, what version of Chart.js are you using? (this plugin requires [Chart.js 2.7.0](/chartjs/Chart.js/releases/tag/v2.7.0))

**Comment by Sadi-1992** [comment]
maybe its n issue of my own project. i think gulp is ignoring dependencies i've installed using npm. i only can se the bower dependencies in my index. o0 will there be an bower package soon?

**Comment by simonbrunel** [comment]
https://chartjs-plugin-datalabels.netlify.com/installation#bower
https://libraries.io/bower/chartjs-plugin-datalabels
