### ISSUE TITLE
Using plugin with RequireJS

### ISSUE THREAD

**Issue by dgambin** [chartjs/chartjs-plugin-datalabels#52]
Hi

I'd like to use the plugin with RequireJS but not sure how to define require.config. I have followed the similar instructions for streaming plugin (https://stackoverflow.com/questions/48957033/what-is-the-syntax-for-require-config-for-chartjs-plugin-streaming-and-dependenc) but wasn't successful.

Any hint?

Thanks very much

regards, dejan

**Comment by simonbrunel** [comment]
@dgambin can you provide the (minimal) code that reproduces your issue (a jsfiddle or a link to your code)? I'm not familiar with RequireJS, so have not clue how it's supposed to be integrated with it.

**Comment by dgambin** [comment]
Seems like exports and map options in shim configuration are relevant for this but I wasn't successful

**Comment by simonbrunel** [comment]
@dgambin following [stackoverflow suggestion](https://stackoverflow.com/a/48958332), it works for me: [jsfiddle](https://jsfiddle.net/simonbrunel/suqtepvs/)

Seems you just need `map`:

```javascript
require.config({
  paths: {
    chart: "//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min",
    datalabels: "//cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.3.0/dist/chartjs-plugin-datalabels.min"
  },
  map: {
    datalabels: {
      "chart.js": "chart"
    }
  }
});

require(["chart", "datalabels"], function(chart) {
  // ... initialize your chart here ...
});
```

**Comment by dgambin** [comment]
Thank you very much. It works!
