### ISSUE TITLE
Overlapping labels with scatter chart

### ISSUE THREAD

**Issue by fishjh2** [chartjs/chartjs-plugin-datalabels#55]
Hi, 
I'm using the plugin with scatter charts and it's doing a great job. However, if there are two scatter points very close together the labels often overlap. Is there any way to avoid this?

Thanks a lot

**Comment by orchestor** [comment]
Could you help provide a codepen link for debugging.

**Comment by simonbrunel** [comment]
There is nothing built-in (yet?) to prevent labels to overlap.

**Comment by simonbrunel** [comment]
Closing this one as duplicate of #72
