### ISSUE TITLE
Showing errors while loading

### ISSUE THREAD

**Issue by navdeepghai1** [chartjs/chartjs-plugin-datalabels#57]
> I am not calling any function from  Charts and Chartjs-plugins-datatable libraries,  I  am not able to understand why it's showing the error  added below in my JS console.

### Error:
> l.update()) : console.error("Failed to create chart: can't acquire context from the given item")

Chartjs Version:

```
 * Chart.js
 * http://chartjs.org/
 * Version: 2.7.2
 *
 * Copyright 2018 Chart.js Contributors
 * Released under the MIT license
 * https://github.com/chartjs/Chart.js/blob/master/LICENSE.md
 ```
```

 * @license
 * chartjs-plugin-datalabels
 * http://chartjs.org/
 * Version: 0.3.0
 *
 * Copyright 2018 Chart.js Contributors
 * Released under the MIT license
 * https://github.com/chartjs/chartjs-plugin-datalabels/blob/master/LICENSE.md
 
```

**Comment by simonbrunel** [comment]
Please share a jsfiddle that reproduces your issue or a link to the page containing the error.

**Comment by navdeepghai1** [comment]
I tried to re-produce the issue, but unable to re-produced it as it was bug in my program. I searched through internet to fix it.

Going to close the issue, as  it's  not related to core library.
