### ISSUE TITLE
only show datalabels when data length is below 8?

### ISSUE THREAD

**Issue by FoleyTim** [chartjs/chartjs-plugin-datalabels#58]
I have a graph comparing 3 years of data, so it has 3 data sets. because of this the data labels tend to overlap. I have a slider for splicing the datasets too. I want to make it so that when the user splices the array to a length below 8 the data labels appear. Is this possible?

**Comment by simonbrunel** [comment]
@FoleyTim did you try with [scriptable options](https://chartjs-plugin-datalabels.netlify.com/options#scriptable-options)?

```javascript
options: {
  plugins: {
    datalabels: {
      display: function(ctx) {
        return ctx.dataset.data.length < 8;
      }
    }
  }
}
```

I'm not sure I get your question though, can you share a jsfiddle with what you have so far?

**Comment by simonbrunel** [comment]
Closing as inactive, feel free to reopen.
