### ISSUE TITLE
hiding zero datalabels

### ISSUE THREAD

**Issue by erenesto** [chartjs/chartjs-plugin-datalabels#6]
Hello,

I have a chart, i am adding an image of it. Is there a chance to hide zero values on bars ?

![chart](https://user-images.githubusercontent.com/18192542/30309356-a1f5aca2-9793-11e7-875b-9f6eac548e15.JPG)

**Comment by simonbrunel** [comment]
You can use scriptable options ([example](/chartjs/chartjs-plugin-datalabels/blob/master/samples/charts/bar.html#L115)):

```javascript
options: {
  plugins: {
    datalabels: {
       display: function(context) {
          return context.dataset.data[context.dataIndex] === 0; // or < 1 or ...
       }
    }
  }
}
```

**Comment by erenesto** [comment]
Thank you very much !

I used `return context.dataset.data[context.dataIndex] > 1;` because i wanted to hide zeros. It's working very well.

**Comment by simonbrunel** [comment]
You right, my snippet was wrong (edited), it should return true if data !== 0 (or >= 1).

**Comment by uffou** [comment]
Awesome! Thanks!

**Comment by davidklebanoff** [comment]
Would it make sense to add this as an official configurable option, since I imagine it's incredibly common?

**Comment by simonbrunel** [comment]
@davidklebanoff I designed scriptable options to actually avoid introducing stuff like `hideWhenZero` which are IMO use case oriented instead of generic options. Adding it built in would require more processing code to guess the actual value and thus more code to maintain for something really easy to implement on the user end. It's also a door opened to options like: `colorAtZero`, `backgroundAtZero`, `colorWhenNegative`, etc. So no, it doesn't make sense to me and I will likely reject any related PR.

If you need this behavior for all your charts, you can setup a global option:

```javascript
Chart.defaults.global.plugins.datalabels.display = function(ctx) {
  return ctx.dataset.data[ctx.dataIndex] !== 0;
}
```

You can also easily implement this option yourself in your projects:

```javascript
Chart.defaults.global.plugins.datalabels.display = function(ctx) {
  var opts = ctx.chart.options.plugins.datalabels;
  return opts.hideWhenZero
    ? ctx.dataset.data[ctx.dataIndex] !== 0
    : undefined;
}
```

Something I could maybe consider however is to expose the value in the context:

```javascript
Chart.defaults.global.plugins.datalabels.display = function(ctx) {
  return ctx.value !== 0;
}
```

**Comment by DynamicArray** [comment]
What about hiding when the label can't be completely displayed? I'm thinking of a measureText call on the canvas ct in the display callback, but I can't find a piece of data that tells me how big the bar (my chart is a vertical bar chart) for the current index is. Any suggestion?

**Comment by jcraigk** [comment]
I'm using Ruby on Rails with `chartkick` to construct Chart.js calls server-side.  That method uses Ruby hashes for configuration (which later get translated to Javascript) and it's not clear how to inject javascript functions using this method.  As this is a fairly common use case, I second the request to have "hiding zeroes" as an option.  Thanks for considering!

**Comment by jaykilleen** [comment]
@jcraigk not sure if you ever sorted this out but for others like us in Ruby land using `chartkick`. 

I followed the recommendation to implement a global option. In my `chart_controller.js` where, using Stimulus, I pickup the options from a json request to a `fetchChartData` type endpoint, I have added the global option like

```
import { Controller } from "@hotwired/stimulus";

import Chart from 'chart.js/auto';
import ChartDataLabels from "chartjs-plugin-datalabels"
Chart.register(ChartDataLabels);

Chart.defaults.plugins.datalabels.display = function(ctx) {
  var opts = ctx.chart.options.plugins.datalabels;
  return opts && opts.hideWhenZero
    ? ctx.dataset.data[ctx.dataIndex] !== 0
    : undefined;
};

export default class extends Controller {
  // ...
}
```

then in my `ChartsController.rb` I pass in the `hideWhenZero` option like 

```
chart = {
      chartName: "example_chart_name",
      type: 'bar',
      options: @chart_options.deep_merge(
        plugins: {
          datalabels: {
            hideWhenZero: true,
          },
        },
      ),
      data: {
        labels: collection.keys,
        datasets: [{
          data: collection.values
        }],
      }
    }

    render json: chart
```
