### ISSUE TITLE
Some labels not showing

### ISSUE THREAD

**Issue by brobey8** [chartjs/chartjs-plugin-datalabels#60]
Hi guys,

I've found an issue where for some reason the labels appear to be getting rendered but then some animation happens and they get pushed off the chart. You can see the issue in [this fiddle](https://jsfiddle.net/1h4nhtq2/79/)

**Comment by simonbrunel** [comment]
Same issue as #15 and #28: bars start from the `0` value, not from the axis, meaning that the bar center is off the canvas. Setting axis `tick.min` highlights the issue ([fiddle](https://jsfiddle.net/1h4nhtq2/83/)).

Closing as duplicate.

**Comment by brobey8** [comment]
@simonbrunel I did manage to figure this one out myself, thanks for the reply. I think the docs should mention this somewhere as it's kind of not obvious, especially if you're hiding the ticks!

**Comment by simonbrunel** [comment]
I think it should be considered as a bug, not a normal behavior.
