### ISSUE TITLE
Last label does not appear fully on Line chart

### ISSUE THREAD

**Issue by rootchips** [chartjs/chartjs-plugin-datalabels#61]
<img width="963" alt="screen shot 2018-06-07 at 4 13 06 pm" src="https://user-images.githubusercontent.com/13043860/41086984-200ddcec-6a6e-11e8-9ef7-3226116dee30.png">

Hi, I tried to adjust font size but it's still does not appear fully on my line chart.

Has anyone already fix this?

Using ```"chartjs-plugin-datalabels": "^0.3.0"```

**Comment by simonbrunel** [comment]
There is nothing built-in to prevent labels to go outside the canvas. Did you try to set some padding on your chart: `options.layout.padding.right: 32px`?

**Comment by rootchips** [comment]
Yeah that solution works! Thanks @simonbrunel 😊
