### ISSUE TITLE
Dynamic Scatter Plot with Label

### ISSUE THREAD

**Issue by orchestor** [chartjs/chartjs-plugin-datalabels#62]
I would like to have data value as a label. I tried different ways.  Can someone help me with this?

https://codepen.io/orchestor/pen/pKEMYZ

**Comment by simonbrunel** [comment]
@orchestor your fiddle doesn't work for me (nothing displayed). Please fix it and provide more context about what doesn't work exactly.

**Comment by orchestor** [comment]
@simonbrunel Here is the right link: https://codepen.io/orchestor/pen/pKEMYZ
I check the examples, all on still cases. I would like to use this plugin to add labels on dynamic scatter plot.

**Comment by simonbrunel** [comment]
You must include the plugin after Chart.js

**Comment by simonbrunel** [comment]
Your example works as expected if you include the plugin **after** Chart.js ([codepen](https://codepen.io/anon/pen/MXZMmj))

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels"></script>
```

Closing as inactive.
