### ISSUE TITLE
Datalabels drawn outside of chart area

### ISSUE THREAD

**Issue by Lenophie** [chartjs/chartjs-plugin-datalabels#64]
Hello !
I have taken notice of the following bug :
![outofchartarea](https://user-images.githubusercontent.com/40424734/41705177-847fa5f0-7538-11e8-8edc-8656fcb4c0dd.jpg)
Datalabels are being drawn outside the chart area when a top legend is used (or any other element that makes the top of the chart area different from the top of the canvas). If this is working as intended, I think there should be a option.

A fix I use when drawing custom lines in chart.js is to clip drawings that go out of the chart area.
Here is an example : 
```js
const ctx = chart.ctx;
const chartArea = chart.chartArea;
ctx.save();
ctx.rect(chartArea.left, chartArea.top, chartArea.right - chartArea.left, chartArea.bottom - chartArea.top);
ctx.clip();
// draw stuff
ctx.restore();
```

**Comment by simonbrunel** [comment]
Fixed in 499dbb70855785aade5286f70a9efeccb6f4a615 and will be available in [v0.4.0](/chartjs/chartjs-plugin-datalabels/milestone/4)
