### ISSUE TITLE
Datalabels not shown in sample files downloaded from github

### ISSUE THREAD

**Issue by Dved85** [chartjs/chartjs-plugin-datalabels#65]
DataLabels ware not showing on my pc even in the sample files I downloaded from the gitbook . Though, the same file when opened on the website, data labels are shown.

**Comment by simonbrunel** [comment]
As explained in [the docs](https://chartjs-plugin-datalabels.netlify.com/installation#download), you need to download the package from the [release page](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v0.3.0) and **not** from the "clone or download" button on the "code/home" page, which is the development version containing only the sources.

**Comment by simonbrunel** [comment]
Assets attached to the release pages work as expected, closing.
