### ISSUE TITLE
autoSkip data Labels

### ISSUE THREAD

**Issue by rootchips** [chartjs/chartjs-plugin-datalabels#67]
<img width="1101" alt="screen shot 2018-06-26 at 2 32 42 pm" src="https://user-images.githubusercontent.com/13043860/41898346-5cad2534-795c-11e8-98ca-c854441e8eb7.png">

Hi, how to autoskip the datalabels if I got a bunch of data?

Eg. 10000 data, I want to display 100 labels only

Tried using this but it didn't work

```
datalabels: {
       display: function (context) {
             return context.dataIndex % 3;
        }
};

**Comment by simonbrunel** [comment]
```javascript
display: function (context) {
    return context.dataIndex % 3;
}
```

This is supposed to work, can you build a jsfiddle that reproduces your issue?

**Comment by rootchips** [comment]
Hi @simonbrunel 

Yeah it does work on 20 datas only

But I tried to show 1000 data, the labels still overlapping over other labels

<img width="916" alt="screen shot 2018-06-26 at 4 37 33 pm" src="https://user-images.githubusercontent.com/13043860/41901973-ddb1eefa-7964-11e8-9f38-d840001fb39b.png">
20 datas

<img width="923" alt="screen shot 2018-06-26 at 4 38 42 pm" src="https://user-images.githubusercontent.com/13043860/41901923-c3ab1784-7964-11e8-9daf-951a0c3ec34f.png">
1000 datas

**Comment by simonbrunel** [comment]
```javascript
display: function (ctx) {
    var capacity = 25;
    var count = ctx.dataset.data.length;
    var step = Math.ceil(count / capacity);
    return ctx.dataIndex  % step === 0;
}
```

This will guarantee to display a maximum of 25 labels whatever the number of data:
- `count <= 25`: all labels are displayed,
- `count > 25`: 1 label every 2 is displayed,
- `count > 50`: 1 label every 3 is displayed,
- `count > 75`: 1 label every 4 is displayed,
- ...

**Comment by rootchips** [comment]
Thank you very much @simonbrunel!

**Comment by simonbrunel** [comment]
Since [v0.5.0](/chartjs/chartjs-plugin-datalabels/releases/tag/v0.5.0) (released today), a better solution could be to use [`display: 'auto'`](https://chartjs-plugin-datalabels.netlify.com/guide/positioning.html#overlap).
