### ISSUE TITLE
Stacked BarChart: do not show labels if stack is to small

### ISSUE THREAD

**Issue by tolik93** [chartjs/chartjs-plugin-datalabels#71]
hi,

i want to show labels on my stacked bar chart dynamicly. 

![canvasstacked](https://user-images.githubusercontent.com/17907942/42265674-7e0ca29a-7f74-11e8-8e15-96c0464257f5.PNG)

The problem is, the labels are displayed always whether the stack has enough place or not. 

```javacript
myNewChart = new Chart(ctx, {
            type: 'bar',
            data: chartData,
            options: {
                responsive: true,
                maintainAspectRatio: false,
                ticks: {
                    beginAtZero: true
                },
                legend: {
                    display: true,
                    position: 'bottom'
                },
                scales: {
                    ticks: {
                        autoSkip: false
                    },
                    xAxes: [{
                        stacked: true,
                        ticks: {
                            autoSkip: false,
                            autoSkipPadding: 20
                        }
                    }],
                    yAxes: [{
                        stacked: true
                    }]
                },
                plugins: {
                    datalabels: {
                        display: true,
                        color: '#fff',
                    }
                }
            }
        }
```

Does anybody have solution for this case?

**Comment by simonbrunel** [comment]
There is nothing built-in, you should use a scriptable option:

```javascript
display: function(ctx) {
  var scale = ctx.chart.scales.y;  // 'y' is your scale id
  var value = ctx.dataset.data[ctx.dataIndex];
  var range = Math.max(scale.max - scale.min, 1);
  return (ctx.chart.height / range) * value > 16;
}
```

`16` is the bar height threshold from which you want to display labels.

https://jsfiddle.net/simonbrunel/3t0cvx6r/

**Comment by tolik93** [comment]
@simonbrunel Thank you. This is nice and simple solution.

**Comment by sivasagiraju** [comment]
Will this resolves the overlapping issue with 2 bars like image
![image](https://user-images.githubusercontent.com/16316594/103545138-291a9b00-4ec7-11eb-8b9d-8403988fc0f2.png)

**Comment by simonbrunel** [comment]
@sivasagiraju No, it will not. Instead you should use [`display: 'auto'`](https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html#overlap) to hide labels that overlap.
