### ISSUE TITLE
Chartjs to build dynamic graph from api data

### ISSUE THREAD

**Issue by SenthilkumarRasan** [chartjs/chartjs-plugin-datalabels#75]
Hi,

I have a API which sends out data for testID. Data has time,transaction name and response time value. Is it possible to dynamically create graph for each transaction in y axis series and plot time in x axis? how do i filter transaction data  and converts to series datapoints with time in xaxis. Thanks

**Comment by simonbrunel** [comment]
@SenthilkumarRasan I don't get how your question is related to this datalabels plugin but you would have better answers asking it on [StackOverflow](https://stackoverflow.com/questions/tagged/chart.js). Chart.js GitHub issues are reserved for bug reports and feature requests.
