### ISSUE TITLE
Show tooltip on clicking datalabel

### ISSUE THREAD

**Issue by soothran** [chartjs/chartjs-plugin-datalabels#79]
Hi 
I would like to show a tooltip on clicking datalabels
Any way to get it done??
Thanks

**Comment by simonbrunel** [comment]
You need to use [events](https://chartjs-plugin-datalabels.netlify.com/events):

```javascript
listeners: {
    click: function(context) {
        // use context.datasetIndex and context.dataIndex
        // to determine what label has been clicked
        // then show tooltip ...
    }
}
```

Implementing / displaying the tooltip is out of the scope of that plugin.
