### ISSUE TITLE
Sample is not running

### ISSUE THREAD

**Issue by mominsamir** [chartjs/chartjs-plugin-datalabels#80]
Sample link is dead.

**Comment by simonbrunel** [comment]
Samples work fine for me (https://chartjs-plugin-datalabels.netlify.com/samples/)

**Comment by grtfou** [comment]
The documentation link is "https://chartjs-plugin-datalabels.netlify.com/samples"
(Github's README.md and documentation page)
So it's not work if it doesn't fix.

"https://chartjs-plugin-datalabels.netlify.com/samples/" will work.
Thank you. :)

**Comment by simonbrunel** [comment]
Thanks @grtfou, fixed in #101
