### ISSUE TITLE
Label overflowing off the canvas when on top of a graph bar

### ISSUE THREAD

**Issue by agrancho** [chartjs/chartjs-plugin-datalabels#88]
I'm having this issue, not sure how to solve it but when a value is too big it overlaps the label out of the canvas (see image in the first and third bar).

Not sure how to it can calculate the height of the label in a way that prevents the bar to build it out of the canvas. Could you help please? :)

![screen shot 2018-09-11 at 11 43 30](https://user-images.githubusercontent.com/14932142/45355334-05294200-b5b8-11e8-9067-ce557ecfb049.png)

Otherwise, congratulations and great work 👍

**Comment by simonbrunel** [comment]
You will need to manually set enough [padding](https://www.chartjs.org/docs/latest/configuration/layout.html?h=padding) around the chart to prevent labels to go out the canvas.

**Comment by agrancho** [comment]
Thanks @simonbrunel , solved 👍

**Comment by Glogo** [comment]
Unfortunately setting layout padding is not helping with chart legend
![image](https://user-images.githubusercontent.com/1913799/97805972-99076d80-1c59-11eb-88b9-ae93d5890133.png)

**Comment by gzhegow1991** [comment]
you have to use "scales.y.grace = '10%'" to set padding dynamically by value offset

**Comment by lyupatov** [comment]
> you have to use "scales.y.grace = '10%'" to set padding dynamically by value offset

thanks a lot!
