### ISSUE TITLE
Conflict with stacked100 plugin on hover

### ISSUE THREAD

**Issue by glenn-barnett** [chartjs/chartjs-plugin-datalabels#89]
Not sure whether to log this here or at https://github.com/y-takey/chartjs-plugin-stacked100, so I'll do both.

chartjs-plugin-stacked100 takes a stacked bar graph, scales the height of all bars to 100%, and changes the labels to show percentage-of-stack values, rather than raw values.

When combined with chartjs-plugin-datalabels, it creates a problem on hover - the datalabels are re-set, changed from the percentage-of-stack value back to the raw values.

Example jsfiddle: https://jsfiddle.net/y9j0ngrd/

**Comment by simonbrunel** [comment]
There is a note about using both plugins, see [README.md, How to use datalabels plugin](https://github.com/y-takey/chartjs-plugin-stacked100#how-to-use-datalabels-plugin) ([fiddle](https://jsfiddle.net/05kz93nw/1/)).

Though, I'm not sure why the data are reset to their original value when hovering bars (@y-takey any idea?)

**Comment by glenn-barnett** [comment]
Thanks - sorry I missed that in the readme.

In some cursory debugging, my observation was that the datalabels plugin was handling the mousemove afterEvent, and reconstructing the labels at that moment, but doing so from raw data.

**Comment by arunfancraze** [comment]
@simonbrunel @y-takey I am facing 1 problem, while writing it in typescript. I am getting a typeError 
`Property 'calculatedData' does not exist on type 'ChartData<keyof ChartTypeRegistry, (number | ScatterDataPoint | BubbleDataPoint | null)[], unknown>'`
You can see the screenshot attached below.
<img width="1440" alt="Screenshot 2023-07-21 at 4 35 54 PM" src="https://github.com/chartjs/chartjs-plugin-datalabels/assets/103022461/88323242-f725-453d-b53f-77180d4ebf83">
