### ISSUE TITLE
Question about anchor and align

### ISSUE THREAD

**Issue by alex-martinez** [chartjs/chartjs-plugin-datalabels#9]
First off, thank you for this great plugin. The docs and samples are awesome.

**Question:**
I'm creating a scatter plot with labels. I have the labels working, however, I can't seem to get them positioned how I'd like. What I want is the text to be centered to the right of the plot point.

**Comment by simonbrunel** [comment]
@alex-martinez It's not possible (yet) to align horizontally for data bound to an horizontal scale, but it's on my todo list to support `align: left|right|bottom|top` in addition to `start|center|end`.

Can you post a screenshot of what you are thinking of exactly?

**Comment by alex-martinez** [comment]
![screen shot 2017-10-13 at 10 07 39 am](https://user-images.githubusercontent.com/2965448/31552953-89636304-affe-11e7-9d24-1cdb836bdf44.png)

I created a small plugin to achieve the affect. There's still more I need to solve such as text ellipses and preventing text overlap.

**Comment by simonbrunel** [comment]
We could also support `align` as a number representing the angle (in degree) in which the label should be shifted away from the anchor point, with the following presets:
- `align: 'right'` -> `align: 0`
- `align: 'top'` -> `align: 90`
- `align: 'left'` -> `align: 180`
- `align: 'bottom'` -> `align: 270`

**Comment by simonbrunel** [comment]
Implemented in ee7723c7dd but not released yet!

**Comment by simonbrunel** [comment]
Released in [v0.2.0](https://github.com/chartjs/chartjs-plugin-datalabels/releases/tag/v0.2.0)
