### ISSUE TITLE
Display one label for each stack in case of stacked group

### ISSUE THREAD

**Issue by Santosh007** [chartjs/chartjs-plugin-datalabels#91]
Hi 

I want to display the total sum of each stacked bar in a chart having, stacked groups. I have referred the https://github.com/chartjs/chartjs-plugin-datalabels/issues/16  which works in case of single stacked bar. I have tried same logic but he output is not as expected (https://jsfiddle.net/Santosh119/bta7zvjs/) . The formatter  runs for each dataIndex and returns on only one value, but in case of groups, single index will have multiple stacked bars, so kindly suggest the solution for this scenario. @simonbrunel

**Comment by Santosh007** [comment]
I was able to find the solution for this, if any one looking for the solution refer https://jsfiddle.net/Santosh119/bta7zvjs/7/

**Comment by mikeover** [comment]
I just want to show the Stack Name along the x-axis above the label. How can I do that?

**Comment by Santosh007** [comment]
@mikeover It's been a while since I last used chartjs, so it might take some time for me to address your query. Meanwhile if you have the link to Codepen or jsfiddle where you are trying to find the solution, share it here so that I can have a look.

**Comment by AlekseyCheCity** [comment]
@Santosh007 thank you a lot!

**Comment by Santosh007** [comment]
> @Santosh007 thank you a lot!

@AlekseyCheCity  welcome :)

**Comment by alundstroem** [comment]
Mb a total thread-gravedigger but I've updated this for the version I happened to use, if anybody else is using ChartJS 3.9.x it might help? See https://jsfiddle.net/v3z5umt0/
