### ISSUE TITLE
"Cannot find name 'Chart'." when trying to overwrite charts default

### ISSUE THREAD

**Issue by shlomiLan** [chartjs/chartjs-plugin-datalabels#92]
I'm using [Ionic](https://ionicframework.com/) to build a mobile app, in it I import the plugin with 
`import 'chartjs-plugin-datalabels';`

Then I want to overwrite the defaults settings with:
`Chart.defaults.global.plugins.datalabels.anchor = 'end';`

When I run my app it seems that everything is working fine, but in the editor (WebStorm) I see the following error:
`TS2304: Cannot find name 'Chart'.`

How can I fix it?
Thanks

**Comment by simonbrunel** [comment]
@shlomiLan did you `import Chart from 'chart.js'` before `chartjs-plugin-datalabels`?
